### PR TITLE
Update divider.scss

### PR DESCRIPTION
**Pull request by Tallyb**
Fix md divider in toolbar

### CODE REVIEW

**Comment by Tallyb** [comment]
I signed it.

**Comment by Tallyb** [comment]
Related to https://github.com/angular/material/issues/2228

**Comment by topherfangio** [comment]
Re-running failed CI build because I think the failure was on our end.

@Tallyb Can you please amend the commit message (and the PR description) to follow our guidelines at https://github.com/angular/material/blob/master/CONTRIBUTING.md#-git-commit-guidelines? Specifically, please tell us how it was incorrect before, how/why your code fixes it, and the related issue numbers?

Thank you!

**Comment by topherfangio** [comment]
@Tallyb Any chance you have the time to update this commit message real fast with what this PR fixes and why? You can use `git commit --amend` to go back and fix a commit message.

Thanks!

**Comment by ThomasBurleson** [comment]
@topherfangio - IMO, this change has dangerous sideaffects. And the author has not responded. Closing.

**Pull request closed without merging**
