### PR TITLE
feat(mdInput): Add right-side icon to input container

### LINKED ISSUE #4763: Add right icon to md-input-container
It would be useful to add support for right icons (or text) for inputs (we should be able to have on both sides) so we can add a percentage icon for example or a currency

### PR DESCRIPTION
**Pull request by programmist**
Fixes #4763

### CODE REVIEW

**Comment by programmist** [comment]
@ThomasBurleson, @jelbourn : Up to date and ready to review.

**Comment by jelbourn** [comment]
LGTM

**Comment by programmist** [comment]
Demo:
https://codepen.io/programmist/pen/dYpwBL

**Comment by ThomasBurleson** [comment]
@programmist :+1:

**Pull request closed without merging**
