### PR TITLE
Make md-select work more like md-input-container/input

### PR DESCRIPTION
**Pull request by MagicIndustries**
Adds required md-input-container to md-select. 
Replaces md-select-label with md-select-value
Adjusts scss to make label transition the same way as with md-input-container/md-input
Removed md-select blacklist from placeholder

### CODE REVIEW

**Comment by thvd** [comment]
I think we get a much nicer diff when you revert the 4 space indent back to the 2 space indent.

**Comment by MagicIndustries** [comment]
Just noticed that, I'm not sure why it's gone in that way, it's 2 spaces in my IDE. I just cloned the repo, added my changes and re-committed. Shouldn't be anything adding extra spaces - I'm on OSX. 

I just checked, in my fork it's two spaces as well. Did I accidentally tick a box somewhere when making the pull request?

**Comment by MagicIndustries** [comment]
Ah, I was checking select, it's the others that were messed up. I'll re-send the pull request.

**Comment by MagicIndustries** [comment]
Never mind, just realised the commit was added to the request :)

**Comment by nantunes** [comment]
You should also try to keep with the project's code style. The diff is polluted with whitespace surrounding the function declarations.

Meanwhile, a cleaner diff: https://github.com/angular/material/pull/3307/files?w=1

Looking forward to the enhancement. :+1:

**Comment by MagicIndustries** [comment]
Thanks for the feedback @nantunes, I've updated the whitespace to remove as much of that noise as possible.

**Comment by dmackerman** [comment]
I'm all about this. I've always been confused by the lack of `<md-input-container>` with selects.

**Comment by dholcombe** [comment]
Thanks for doing this. I just implemented something similar in my site (the CSS portions anyhow). This more complete solution will be helpful when it ships.

**Pull request closed without merging**
