### PR TITLE
fix(datepicker): validation error when adding text after date

### LINKED ISSUE #9994: datepicker: validation behaves differently in IE
**Actual Behavior**:
You can test it here in angular material demos for IE and Chrome:
https://material.angularjs.org/1.1.1/demo/datepicker
 The issue is when you input an invalid value in the date picker in IE with ngMessages, it says "Only Weekends are allowed", then when you add a letter in the input, it doesn't validate it (for example 11/9/2016 and after that input a letter, 11/9/2016t). I was expecting to have this message showed "The entered value is not a date!" but it didn't. It wasn't happening when I was using Angular Material 1.0.8.
In Chrome, it validates correctly so if you add a letter in datepicker input, it says "The entered value is not a date!". This only became an issue from angular material 1.1.0 in IE.

** steps to reproduce the issue**
 -  https://material.angularjs.org/1.1.1/demo/datepicker
 -  `Details:` adding a letter in input "With ngMessages", the validation message stays "Only Weekends are allowed" instead of "The entered value is not a date!".

### PR DESCRIPTION
**Pull request by Splaktar**
## PR Checklist
Please check that your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-commit-message-format)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
this fixes a regression introduced in v1.1.0 against IE
however the test is able to reproduce the issue on Chrome

Issue Number: 
Fixes #9994. Closes #10520. Relates to #10015.

## What is the new behavior?
The test passes and datepicker validation and ngMessages work properly on IE.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
thank you to Topher Fangio and Richard Hughes for the original solution

### CODE REVIEW

**Comment by mmalerba** [comment]
There is a single failing screenshot test for this PR. It shows a form with a start and end date both set to the same date and the submit button disabled (it was not disabled prior to this PR). Then after clicking the dialog that is supposed to pop up no longer does.

**Comment by Splaktar** [comment]
@mmalerba I just wanted to confirm that this form is made up of two datepickers? One for start date, one for end date?

**Comment by Splaktar** [comment]
@mmalerba Is this a valid reproduction case? https://codepen.io/Splaktar/pen/rdLdGQ

**Comment by mmalerba** [comment]
@Splaktar that looks like the page I was seeing, but obviously its working fine there. We'll probably need to dig into the code for that particular failing test

**Comment by Splaktar** [comment]
@mmalerba I would love to unblock this PR so that we can fix this **Urgent Regression** issue. Do you have any additional feedback that could help us identify how to reproduce this screenshot failure? Is this an application-specific bug?

**Comment by Splaktar** [comment]
@jelbourn if you get a chance, can you please provide some details to allow me to resolve the one internal breakage on presubmit for this urgent regression PR that has been blocked since April?

**Comment by Splaktar** [comment]
The only information that I have on these presubmit failures is that they are failing on internal Google e2e tests that will require further investigation and debugging by a caretaker.

The failures look like this ` - Expected $.length = 4 to equal 0.` which is not overly helpful for debugging externally.

Bumping this to the next release again.

**Pull request merged**
