### PR TITLE
feat(chips): Add `md-on-remove` attribute.

### LINKED ISSUE #3190: mdChip : onDelete event on Chips
Hi,
I have noticed there is a parameter onAppend parameter to the Chips component allowing me to know when a new element is added.
However, I can't see any way to get notified when an element is deleted from the Chips.
Would it be possible to have a similar parameter to be able to know when an element has been removed ?

### PR DESCRIPTION
**Pull request by topherfangio**
Users have requsted a way to be notified when a chip is removed
from the list.

closes #3190

### CODE REVIEW

**Comment by topherfangio** [comment]
@typotter ready for review :-)

**Comment by typotter** [comment]
Excellent! LGTM

**Comment by lscordilis** [comment]
I'd love to contribute an example of ```md-on-remove``` to the docs :) https://material.angularjs.org/latest/#/demo/material.components.chips

**Comment by topherfangio** [comment]
@lscordilis You can definitely send us a PR! We love doc-related PRs :-)

Make sure to check our [Contributing](https://github.com/angular/material#contributing) section about best practices and the necessary steps.

**Pull request closed without merging**
