### PR TITLE
fix(sidenav): fix delayed animation for sidenav if scrollTop != 0

### LINKED ISSUE #5850: md-sidenav was delayed
When I scroll down and open the `md-sidenav`, the `md-sidenav` was delayed.

default

### PR DESCRIPTION
**Pull request by DevVersion**
To checkout:
- Old Version: http://codepen.io/Shyam-Chen/pen/KdYdme
- New Version: http://codepen.io/DevVersion/pen/KdYxbK

Fixes #5850

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@EladBezalel - can you review please.

**Comment by EladBezalel** [comment]
@DevVersion IMO this is a partial fix for a bigger problem.

as a user i won't expect the contect to jump to head when sidenav got open.

@ThomasBurleson thoughts?

**Comment by DevVersion** [comment]
@EladBezalel As the current behaviour, its scrolling after the animation to the top, so the user thinks it appearing with a delay.
After this fix it scrolls at first and the animation looks perfect.

**Comment by EladBezalel** [comment]
@DevVersion yes is can see that, can you make a little effort and see if there's a way of preserving the scroll? i think it would be for the best.

@ThomasBurleson LGTM

**Comment by DevVersion** [comment]
@EladBezalel I'm trying to get into this, if we want to show the animation on scrolled content too, we should display the sidenav fixed in a wrapper otherwise the sidenav is fixed to the body of the page.

Any other solutions or ideas?. We should provide this temporary fix (it isn't doing something bad. it only fixes a bug with a good solution). But as you and I prefer we should provide a **PERFECT** solution.

**Comment by EladBezalel** [comment]
Sidenav should have fixed position that should't affect the content..

**Comment by DevVersion** [comment]
@EladBezalel This is a fix, already tested by me on Chrome, which works :smile: Can you please review that?

**Comment by EladBezalel** [comment]
@DevVersion I pulled your change and tested with the codepen from above and its still seems to jump to the start

**Comment by EladBezalel** [comment]
Closing as #5887 has a better outcome

**Pull request closed without merging**
