### PR TITLE
build(ci): use 'dots' karma reporter on Travis

### LINKED ISSUE #3628: Use 'dots' reporter on Travis builds
The 'progress' output on travis becomes a spammy unreadable mess, so it would be good to use 'dots' instead.

### PR DESCRIPTION
**Pull request by caitp**
Much easier on the eyes

Closes #3628

### CODE REVIEW

**Comment by caitp** [comment]
looking at the travis output, it's still not using the dots reporter, so this didn't quite work

**Comment by ThomasBurleson** [comment]
Just notice that myself. Will you investigate ?

**Comment by caitp** [comment]
yeah i'll take a look

**Comment by ThomasBurleson** [comment]
Appears to be in the `karma.conf.js`:

`reporters: ['dots'],`

**Comment by caitp** [comment]
it's possible to do it in the configs, but progress reports are nice locally, just hard to read on travis. I've updated the gulp tasks to overwrite with the argument-specified value if present

**Comment by caitp** [comment]
works now, closely matches the angular 1.x ci builds

**Pull request closed without merging**
