### PR TITLE
feat(core) create mdResolve service

### PR DESCRIPTION
**Pull request by ivnivnch**
The $mdResolve service helps to resolve acyclic dependencies (ui.router like resolve).
Used internally in $mdCompiler service.

Now you can do this:

```js
$mdCompiler.compile({
  locals: {
    value: 'value'
  },
  resolve: {
    asyncService: function(value, $q) {
      return $q.when(value);
    },
    service: function(value, asyncService ) {
     return value == asyncService;
    }
  },
  ...
});
```

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@jelbourn - want to review this with me ?

**Comment by ThomasBurleson** [comment]
References https://github.com/angular/material/commit/bee05239014e5eb8a0ae1b9e842f32c9caa9474b#commitcomment-12119240

**Comment by ivnivnch** [comment]
Changed the behavior of $mdResolve:
* Promises can be passed to the controller via locals.
* Locals passed by reference.
```javascript
var value = 'value';
var promise = $q.when('promise');
$mdCompiler.compile({
  locals: {
    localValue: value,
    localPromise: promise
  },
  resolve: {
    first: $q.when('first'),
    second: function($q, localValue, localPromise) {
      return $q.when(localValue == value &&
        localPromise == promise && isPromise(localPromise) &&
        'second');
    },
    third: function(first, second) {
      return !isPromise(first) && first == 'first' &&
        !isPromise(second) && second == 'second' &&
        'third';
    }
  },
  controller: function(localValue, localPromise, first, second, third) {
    assert(localValue == value);
    assert(localPromise == promise && isPromise(localPromise));
    assert(!isPromise(first) && first == 'first');
    assert(!isPromise(second) && second == 'second');
    assert(third == 'third');
  }
});
```

**Comment by ThomasBurleson** [comment]
@ivnivnch - what specific problem do these changes solve for you? Can you provide a demo/plunkr ?

**Comment by ivnivnch** [comment]
[$mdResolve example](http://plnkr.co/edit/SgDdaT8mqMjxhc74iBHN?p=preview). Pay attention to the MainController.search method. Without $mdResolve, I get an [error](http://plnkr.co/edit/wZyepho0e6RHw5vASlaI?p=preview), or there is a a [bad solution](http://plnkr.co/edit/SmNDwaxe8n0mYWZC6iEK?p=preview).

**Comment by ThomasBurleson** [comment]
@ivnivnch - Your two (2) demos were very helpful. Thank you.

I would not consider promise chaining and *temp* closure variable a **bad** solution; in fact, I think it is a **classical** solution. Nevertheless, it is not ideal **AND** it would be nice to support both the **resolve** and the **classical** approaches.

**Comment by gkalpak** [comment]
I, too, don't get what is so bad about the _"bad solution"_. (It can get a little cleaner, but no big deal: [Updated plnkr][1]).

In any case, having resolvable objects that depend on other resolvable objects is quite of an edge-case imo and although nice-to-have, I am not sure if it's worth the compexity (more complex code, more edge-cases to get right, less maintainable, less easy to reason about).

I am not saying I am against it - I'm just not convinced (yet) :smile: 

[1]: http://plnkr.co/edit/3WM14gy24rkpfNk4AP1h?p=preview

**Comment by ivnivnch** [comment]
@ThomasBurleson Yes, perhaps it would be better to call the good, the bad and the ugly :smile:. This pull request not break backwards compatibility and supports classical approaches, as You can see in the tests. Also the same approach is used in the ui.router, and developers using ui.router will not be surprised. On the contrary, I was surprised that this feature is not working.

**Comment by ivnivnch** [comment]
@gkalpak it works, but it looks too confusing.

**Comment by EladBezalel** [comment]
@ivnivnch can you please rebase?

**Comment by ivnivnch** [comment]
I already deleted my fork.

**Pull request closed without merging**
