### PR TITLE
feat(md-chips): re-added validation for ng-required

### PR DESCRIPTION
**Pull request by Splaktar**
## PR Checklist
Please check that your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-commit-message-format)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
```
[x] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
#11125 had to be reverted due to regression #11217.

Issue Number: 
#11217

## What is the new behavior?
This includes #11125 plus the regression fix for #11217.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
N/A

### CODE REVIEW

**Comment by Splaktar** [comment]
@IMM0rtalis can you please take a look and confirm that this is OK?

**Comment by IMM0rtalis** [comment]
@googlebot I confirm.

**Comment by IMM0rtalis** [comment]
@Splaktar the fix of yours works for me.

But I do not really get why we validate the model in `shouldAddOnBlur`. The model is not even set here, right? So it validates the model before adding (so validates the existing ones). If I am right (and do not oversee sth) I think the logic is wrong. 
Only thing which could be validated here would be a copy of the model which then includes the new element and validate then. If valid -> add, if not, do not add.

**Comment by Splaktar** [comment]
I actually tried to remove the call to `validateModel()` from `shouldAddOnBlur()` and just check for `!hasMaxChipsReached()`, but that caused a couple tests to fail. Part of this is because `appendChip()` already calls `validateModel()`. So for the add on blur case, `validateModel()` is always called twice. 

One of the existing tests just directly calls `$setValidity('is-valid', false)` and doesn't depend on the `md-max-chips` validity. I'm unclear exactly what the use case could be there.

From what I can tell the valid model check is only there so that a chip doesn't get added when `md-max-chips` has been reached. But we have tests that go beyond that and it's unclear why, but I'm not comfortable removing those tests as users may be relying on that behavior.

**Comment by IMM0rtalis** [comment]
I also just looked into the tests and I still think fixing the blur-function would be a good improvement. But this would be out of scope for this fix anyway.

**Pull request merged**
