### PR TITLE
fix(chips): do not display broken image when no image is provided

### PR DESCRIPTION
**Pull request by Frank3K**
When no image property is defined on the user model, do not render an `img`-element.

References #4779.

### CODE REVIEW

**Comment by topherfangio** [comment]
Any chance you can provide some pictures on how this looks with some items having a valid image and some not? I'd like to make sure that it looks consistent both ways.

**Comment by Frank3K** [comment]
Current display state when there is no image for the contacts [codepen](https://codepen.io/anon/pen/gaLLYb). Chrome 45, Firefox 40 and Internet Explorer 11 show the complete `alt` text here, which messes with the layout.

Demo with new code follows asap.

**Comment by topherfangio** [comment]
Okay; I think that looks pretty good. Can you add a quick set of unit tests for this change? Basically, just check that if the image is provided, the element has the `` tag, and if not, it doesn't?

**Comment by Frank3K** [comment]
@topherfangio: done.

**Comment by topherfangio** [comment]
@ThomasBurleson LGTM :-)

**Pull request closed without merging**
