### PR TITLE
fix(dialog): rename content to textContent

### LINKED ISSUE #5722: Dialog "Open From Close To"
In the just released 1.0.0rc4 version, the demo page for dialogs, section "Open From Close To" doesn't display any dialog due to errors.

### PR DESCRIPTION
**Pull request by DevVersion**
Bug introduced at 6a564508567cf1e352495bdf803f6db94334c601

Fixes #5722 #5792

### CODE REVIEW

**Comment by jelbourn** [comment]
Thanks!

**Comment by DevVersion** [comment]
Created another commit, which fixes #5792 too, commits successfully squashed :smile:

**Comment by jelbourn** [comment]
Went to merge this now, then saw that @rschmukler already made the same change.

**Comment by DevVersion** [comment]
Okay, no problem :smile:

**Pull request closed without merging**
