### PR TITLE
feat(chips): Make chips editable

### PR DESCRIPTION
**Pull request by mertdeg2**
26064e3c-d956-11e5-83e1-fcc6c644fc6f

### CODE REVIEW

**Comment by mertdeg2** [comment]
@DevVersion @ThomasBurleson I have ended up deleting the old branch and creating a new one. Please disregard my other requests.

**Comment by DevVersion** [comment]
As said in the previous PR, LGTM

**Comment by gpopovic** [comment]
Does this work with md-chips using autocomplete or only md-chips using input?

**Comment by ThomasBurleson** [comment]
Fixed with SHA c3085ee

**Pull request merged**
