### PR TITLE
refactor: Revert CSS privatization.

### PR DESCRIPTION
**Pull request by topherfangio**
Revert previous changes to privatize much of our CSS.

> See public announcement [**Revisiting the decision to rename private CSS classes in 1.1**](https://groups.google.com/forum/#!msg/ngmaterial/mLJrRW9qrLA/C_Ni3LSrBQAJ)

Also fixes an erroneously passing chips test.

### CODE REVIEW

**Comment by clshortfuse** [comment]
I ran a grep and found a few you've missed

src/components/progressLinear/progress-linear.spec.js:112:      expect(progress.hasClass('_md-progress-linear-disabled')).toBe(true);
src/components/progressCircular/progress-circular.spec.js:106:    expect(element.hasClass('_md-progress-circular-disabled')).toBe(true);
src/components/toolbar/toolbar.js:76:        element.addClass('_md-toolbar-transitions');     // adding toolbar transitions after digest
src/components/panel/panel.js:1168:      self._panelEl.addClass('_md-panel-fullscreen');
src/components/panel/panel.js:1438:    this.addClass('_md-panel-shown');
src/components/panel/panel.js:1466:    this.removeClass('_md-panel-shown');
src/components/navBar/navBar.js:237:  this._inkbar.toggleClass('_md-left', newIndex < oldIndex)
src/components/navBar/navBar.js:238:      .toggleClass('_md-right', newIndex > oldIndex);
src/components/menuBar/menu-bar.spec.js:18:        expect(element.hasClass('_md')).toBe(true);
src/components/menuBar/js/menuBarDirective.js:127:        el.addClass('_md');     // private md component indicator for styling
src/components/chips/js/chipController.js:69:    this.getChipContent().addClass('_md-chip-content-edit-is-enabled');
src/components/chips/js/chipController.js:106:  this.$element.removeClass('_md-chip-editing');
src/components/chips/js/chipController.js:153:  this.$element.addClass('_md-chip-editing');
src/components/fabSpeedDial/fabSpeedDial.js:125:      if (element.hasClass('md-animations-waiting') && !element.hasClass('_md-animations-ready')) {
src/components/list/list.js:334:          tEl.addClass('_md-button-wrap');
src/components/list/list.js:431:            isButtonWrap  = $element.hasClass('_md-button-wrap'),
src/components/list/list.spec.js:153:    expect(listItem).toHaveClass('_md-button-wrap');
src/components/list/list.spec.js:179:    expect(listItem).toHaveClass('_md-button-wrap');
src/components/list/list.spec.js:205:    expect(listItem).toHaveClass('_md-button-wrap');
src/components/list/list.spec.js:230:    expect(listItem).toHaveClass('_md-button-wrap');
src/components/list/list.spec.js:255:    expect(listItem).toHaveClass('_md-button-wrap');
src/components/list/list.spec.js:272:    expect(listItem).toHaveClass('_md-button-wrap');
src/components/list/list.spec.js:292:    expect(listItem).toHaveClass('_md-button-wrap');
src/components/list/list.spec.js:317:    expect(listItem).toHaveClass('_md-button-wrap');
src/components/list/list.spec.js:349:    expect(listItem).toHaveClass('_md-button-wrap');

src/components/panel/panel.js:601:    '<div class="_md-panel-focus-trap" tabindex="0"></div>');
src/components/navBar/navBar.js:109:          '<ul class="_md-nav-bar-list" layout="row" ng-transclude role="listbox"' +
src/components/navBar/navBar.js:392:        '<md-button ng-if="ctrl.mdNavSref" class="_md-nav-button md-accent"' +
src/components/navBar/navBar.js:396:          '<span ng-transclude class="_md-nav-button-text"></span>' +
src/components/navBar/navBar.js:398:        '<md-button ng-if="ctrl.mdNavHref" class="_md-nav-button md-accent"' +
src/components/navBar/navBar.js:402:          '<span ng-transclude class="_md-nav-button-text"></span>' +
src/components/navBar/navBar.js:404:        '<md-button ng-if="ctrl.mdNavClick" class="_md-nav-button md-accent"' +
src/components/navBar/navBar.js:408:          '<span ng-transclude class="_md-nav-button-text"></span>' +
src/components/fabSpeedDial/fabSpeedDial.js:116:      element.prepend('<div class="_md-css-variables"></div>');

I just wanted to play with grep :-P I'm going to try my hand at a regex for this

**Comment by topherfangio** [comment]
@clshortfuse Thanks for the printout. Most of those are actually legitimate though. I only reverted the ones that we **changed** after the 1.0 release. Some (especially the panel/navbar) were private classes that will be added in 1.1.0, but weren't available in 1.0.0, so I left them as-is.

Additionally, there were two classes that I think definitely **should** be private as they are for use by the internal workings of the FAB speed dial, so I left them.

That said, it looks like I did miss a few with the chips and the chip remove container, so I'm working to fix those. Incidentally, that's why the build is failing, but I need to touch base with @DevVersion about one of the changes real fast before I can fix it.

@ThomasBurleson I'm marking this as "Needs Work", but I should have it fixed/ready early tomorrow.

**Comment by topherfangio** [comment]
@ThomasBurleson I fixed the failing tests; this should now be ready for review.

**Comment by ThomasBurleson** [comment]
@topherfangio - LGTM. Merging on July 11. 
> See public announcement [**Revisiting the decision to rename private CSS classes in 1.1**](https://groups.google.com/forum/#!msg/ngmaterial/mLJrRW9qrLA/C_Ni3LSrBQAJ)

**Comment by david-gang** [comment]
Hi @topherfangio ,

Do you have a list of all css classes which were reverted from private to public?
We already changed all classes, and now this would mean that we have to review the whole application again.
Getting a list would enable us to create a script which makes the automatic conversion.

Thanks,
David

**Comment by ThomasBurleson** [comment]
@daniel-nagy  - I do not understand "we already changed all classes". Which classes? 

If you mean you were overriding private CSS and when those were privatized you added `_` prefixes to your custom overrides?

**Comment by david-gang** [comment]
Yes @thomasburleson but at the time I used them they were not private, so I relied on them and now that they are public again I can use them again, so I just need a list of all css variables where the privatization was reverted

**Comment by ThomasBurleson** [comment]
@david-gang - regardless of our removal of the "_" prefix, I would recommend that you should not use these classes unless you **absolutely** need to.

> We are working to prepare a list of changed CSS classnames and types affected.

**Pull request closed without merging**
