### PR TITLE
Fix attribute directives (layout, flex, etc) observe attribute value

### PR DESCRIPTION
**Pull request by langan**
I think this fixes the issue #4622, the attribute value wasn't being observed so the $observe code wasn't being executed when the attribute value changed.

### CODE REVIEW

**Comment by langan** [comment]
@ThomasBurleson will this be added in the 0.11.1 release?

**Comment by ThomasBurleson** [comment]
@langan - in the future, please do not replace the string quotes. That creates huge `diff clutter`

**Comment by ThomasBurleson** [comment]
This feature will be in the next release: v0.11.1-rc1 and greater.

**Comment by langan** [comment]
@ThomasBurleson whoops sorry, just thought it looked odd using double quotes on those particular lines when the majority of code uses single.

Will make sure it doesn't happen again.

There is nothing in the [coding styles](https://github.com/angular/material/blob/master/docs/guides/CODING.md) about quotes.

Do you need me to add any unit tests for observing a variable?  Looks like layout.spec.js doesn't cover that case at the moment.

**Comment by ThomasBurleson** [comment]
See pending PR https://github.com/angular/material/pull/4698/files#diff-08c7a16dd7bb0b15845b6b6b6ae637c5R191 for the process to watch interpolated attribute values.

**Comment by ThomasBurleson** [comment]
Merged and closed with SHA 7264cab40349

**Pull request closed without merging**
