### PR TITLE
adds the option to the user to search for partial in autocomplete

### PR DESCRIPTION
**Pull request by beardyco**
This gives the user the option to search and return partial or complete matches.
        /**
         * Searches state to find a partial match for string
         */
        return state.value.match(lowercaseQuery); 
        /**
         * Searches state to find a complete match for string
         */
        return (state.value.indexOf(lowercaseQuery) === 0);

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@DevVersion - do you not have a PR for this already?

**Comment by DevVersion** [comment]
@ThomasBurleson No, that's the first PR for this feature.

**Comment by ThomasBurleson** [comment]
@beardyco - please rebase and provide 2-3 unit tests.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Pull request closed without merging**
