### PR TITLE
feat(calendar) month selector for calendar clarity

### LINKED ISSUE #4251: md-datepicker should have option to select year and month
If we have to select future of past dates, (date of birth of something), it is difficult to scroll up and down. Should have selection of year and month.

### LINKED ISSUE #5779: Select year support in md-datepicker
screen shot 2015-11-17 at 1 39 28 pm

### PR DESCRIPTION
**Pull request by DevVersion**
## Summary 
Month Selector containing:
- Forward Month
- Backward Month
- Current Visible Month and Year (calculation)
- Calendar Tests for the new features

## Questions and Examples
**How is it looking?**
- 

**What happens when I scroll?**
- 

**What happens when I click on the arrows?**

Fixes #5779 Fixes #4251

### CODE REVIEW

**Comment by DevVersion** [comment]
This is the old Version which only contains the Month Selector (this is also ready for merge).
My new PR, which is completely redesigning the Datepicker and Calendar is including this PR

If you are interested in looking at the new PR / Design see here #5971

**Comment by jelbourn** [comment]
As I described in #5971, we're not going to change the appearance of he datepicker, but I am still trying to work with our UX designers on an approach to make the scrolling / month transitioning more apparent.

**Comment by ramirezd42** [comment]
@jelbourn I get not wanting to deviate from the UX team's spec, but scrolling of the month only solves half the issue. Picking a year is an incredibly common scenario (Date of birth?) that is currently only supported by writing the date in manually. 

Are there any plans to add a year selection feature in addition to the month scrolling?

**Comment by jelbourn** [comment]
@ramirezd42 #4251

**Pull request closed without merging**
