### PR TITLE
feat(autocomplete): add md-input-class binding.

### PR DESCRIPTION
**Pull request by VictorioBerra**
Works similarly to the md-menu-class binding.

### CODE REVIEW

**Comment by VictorioBerra** [comment]
I signed it!

**Comment by eknowles** [comment]
Hi @VictorioBerra you might need to add a new test case here

**Comment by VictorioBerra** [comment]
@eknowles tests added.

**Comment by Splaktar** [comment]
Thank you for your contribution. Please follow the [commit message guidelines](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-commit-message-format).

**Comment by VictorioBerra** [comment]
@Splaktar commit messages updated.

**Comment by Splaktar** [comment]
Please squash your commits.

**Comment by VictorioBerra** [comment]
Okay I have royally screwed this up trying to squash these commits and force pushing the new history. I am going to have to abandon this PR entirely, re-fork, apply stash and resubmit.

**Comment by Splaktar** [comment]
No problem, thank you for putting up the new PR.

**Pull request closed without merging**
