### PR TITLE
fix(sticky): compile cloned element in the same scope

### LINKED ISSUE #4979: mdSticky: directive with scope params lose assignment
Hi,

i have a directive which has different kinds of scopes. If the mdSticky component clone the directive, the scope values will be lost. But it is nessecary that the scope state stay active.

That is my directive:

```javascript
subnavigation.directive('subNavigation', function($mdSticky){
	return {
		restrict: 'E',
		replace: true,
		scope: {
			navigate: '&',
			activeComponents: '=',
			versions: '=',
			tariffs: '=',
			settings: '='
		},
		templateUrl: 'Resources/Public/js/app/shared/directives/subnavigation/subnavigation.html',
		link: function (scope, element) {
			$mdSticky(scope, element);
		}
	};
});
```

```html
<md-content>
			<sub-navigation navigate="bootstrap.navigateTo(component)" versions="versions"
			                active-components="activeComponents" tariffs="tariffs" settings="settings"></sub-navigation>
...
</md-content>
```

Do i something wrong or is this a bug?

### PR DESCRIPTION
**Pull request by DevVersion**
Currently never apply a scope to the cloned element, which will cause problems with directives, which have bindings in their template.

Also added the documentation for a common use-case

Closes #4979

### CODE REVIEW

**Comment by EladBezalel** [comment]
Code LGTM

**Comment by DevVersion** [comment]
@EladBezalel Yep, just referenced now :)

**Comment by Sriram143** [comment]
this is missing

  MdSticky.$inject = ["$document", "$mdConstant", "$$rAF", "$mdUtil", **"$compile"]**;

**Comment by DevVersion** [comment]
@Sriram143 No need, this will be automatically added through the build process, using ngAnnotate.

**Comment by Sriram143** [comment]
@DevVersion  Thanks for the update.

**Comment by david-meza** [comment]
Thanks for the contribution. I am running into this issue at the moment. Will this still work with more complex templates that use transclusion and/or inner components which have to compile (say, `md-icon`). Thank you.

**Comment by DevVersion** [comment]
@david-meza The new changes won't change anything huge in the service. As mentioned in the documentation, we will compile the cloned directive by default into the provided scope. At this point there can be problems with already-compiled elements which change their structure during compilation. 

So for example if I use a directive template like:
```html
<my-directive>
  Hello
</my-directive>
``` 
and the actual directive will modify the element tree, to look like this:
```html
<my-directive>
  <div class="wrap-container">
    Hello
  </div>
</my-directive>
```
then we'll have a problem with compiling that back into the element tree. The `compilation` of the cloned element is required, to reapply the specified scope to the cloned element.

If this is your case, that the directive can't detect the actual content anymore - then you have to use the plain template as shown in the example.

So finally I can say, this is a good question and isn't easy to solve, because we have no way to detect the initial DOM structure or copying all the needed `controllers` / `directives` back to the cloned element.

**Pull request closed without merging**
