### PR TITLE
upd autocomplete template placeholder optional

### PR DESCRIPTION
**Pull request by Ariesly**
use md-input-container with autocomplete float label
<md-input-container>
  <label>Contact Chips</lable>
  <md-contact-chips ...></md-contact-chips>
</md-input-container>

### CODE REVIEW

**Comment by Ariesly** [comment]
I signed it!

**Comment by Ariesly** [comment]
I signed it!

**Comment by Ariesly** [comment]
I signed it!

**Comment by ThomasBurleson** [comment]
There is not an issue associated with this PR nor any unit tests to verify the fix.
Closing as an invalid PR.

**Pull request closed without merging**
