### PR TITLE
fix(checkbox): center label text vertically when font size is changed

### PR DESCRIPTION
**Pull request by cempehlivan**
## PR Checklist
Please check that your PR fulfills the following requirements:
- [x] The commit message follows [our guidelines](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-commit-message-format)
- [x] Tests for the changes have been added or this is not a bug fix / enhancement
- [x] Docs have been added, updated, or were not required

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Enhancement
[ ] Documentation content changes
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #11995 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by cempehlivan** [comment]
@googlebot I signed it!

**Comment by Splaktar** [comment]
Thank you for your contribution! Can you please update your commit message to follow our [commit message guidelines](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-commit-message-format)? 

```
fix(checkbox): center label text vertically when font size is changed

Fixes #11995
```

**Comment by cempehlivan** [comment]
Ok, changed it.

**Review by Splaktar — CHANGES_REQUESTED** [review]
This change seems to break vertical positioning of checkbox labels.

## Before

Screen Shot 2020-09-22 at 19 42 52

## After

Screen Shot 2020-09-22 at 19 43 16

**Comment by Splaktar** [comment]
I took a longer look at this and wrote up a summary [here](https://github.com/angular/material/issues/11995#issuecomment-739440405). We'll need to take a different approach than the one used in this PR.

**Pull request closed without merging**
