### PR TITLE
fix(tabs): Icon color isn't correct when the tab item is not active

### LINKED ISSUE #9536: tabs: icon color isn't correct when the tab item is not active
When the tab isn't focused the icon color isn't the same as the text color.
[CodePen](http://codepen.io/EladBezalel/pen/rrNXPA)

linking #9502

### PR DESCRIPTION
**Pull request by olegoode**
- Adds icons to a demo.
- Fixes typo in aforementioned demo.
- Corrects color of icons in a disabled/non-focused tab label.

Closes #9536

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@EladBezalel - please review.

**Comment by EladBezalel** [comment]
@olegoode please squash your commits

**Comment by olegoode** [comment]
@EladBezalel Done.

**Comment by EladBezalel** [comment]
@olegoode sorry for the delay, LGTM

**Pull request merged**
