### PR TITLE
fix(toolbar): solves NgUpgrade interop issue. Fixes #6069

### LINKED ISSUE #6069: Can't use mdToolbar directive with NgUpgrade
NgUpgrade UpgradeAdapter#upgradeNg1Component fails with ```Error: Directive 'mdToolbar' is not a component, it is missing template.``` NgUpgrade throws this error if a component (aka directive) does not have either a 'template' or 'templateUrl' in its DDO. Where is the mdToolbar html coming from then?

Please, if there's anything I can do to get this working, I'd be glad to help

### PR DESCRIPTION
**Pull request by alex94puchades**
I know development is currently focused on ng2, but these changes are so minor it can't hurt

### CODE REVIEW

**Comment by alex94puchades** [comment]
I signed it!

**Comment by alex94puchades** [comment]
PR now passes all tests. It depends on https://github.com/angular/angular/pull/5604

**Comment by ThomasBurleson** [comment]
@jelbourn - Seems like something to have **before** our v1.0.0 release. thoughts ?

**Comment by jelbourn** [comment]
LGTM, this is fine

**Pull request closed without merging**
