### PR TITLE
fix(card): fix style for .md-subhead class when not only child

### LINKED ISSUE #8431: mdCard: .md-subhead:only-child classes
**Actual behavior**:
-  What is the issue?

With only md-card-title-text in md-card-title component, a .md-subhead tag is always styled as if it had no sibling
-  What is the expected behavior?

When with another sibling, the .md-subhead should be small, grey and have no padding-top applied

**Steps to reproduce the issue:**
-  See the "Card with image - Extra Large" on [documentation](https://material.angularjs.org/latest/demo/card). The subhead is black and lower than expected to be.

image

**Angular Versions**:
-  Angular Version: 1.5.5
-  Angular Material Version: 1.1.0-rc4

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 50.0.2661.94 m
-  OS: Win7

### PR DESCRIPTION
**Pull request by tyrsensei**
Apply style when no md-card-title-media

fixes #8431.

### CODE REVIEW

**Comment by EladBezalel** [comment]
Sgtm needs local testing

**Comment by ThomasBurleson** [comment]
@EladBezalel - did you test these locally ?

**Comment by EladBezalel** [comment]
LGTM

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Pull request closed without merging**
