### PR TITLE
update(changelog): improve listing of breaking changes.

### LINKED ISSUE #2466: Please don't forget to write about breaking changes
Commit b0c9f9f19fc6fdfa7c585e1a7431f6f2ce5d1573:
screenshot 2015-04-21 21 32 04

Commit 77c9cc37f6ddc56df4ea94600fb39ed7abc68131:
screenshot 2015-04-21 21 34 15

Markup was made with md-list, md-content, md-item.
But 0 breaking changes, related to md-list or md-item between these commits... So what has been changed? Will take a shovel and dig, step by step, to find it...

### PR DESCRIPTION
**Pull request by ThomasBurleson**
Fixes #2466

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@marcysutton, @rschmukler, @robertmesserle - Can you think of any other breaking changes for RC2 (or RC3 when that is released)?

**Comment by robertmesserle** [comment]
@ThomasBurleson I noted it as a breaking change in my commits, but Tabs have been fully rewritten and include breaking changes since 0.8.3

**Comment by ThomasBurleson** [comment]
Any other items (on Tabs) that we should explicitly list in the changelog?

**Comment by jamm** [comment]
@robertmesserle only noted change about tabs is 

> When using md-tab-label, the content of your tab must be wrapped in md-tab-body

nothing else. If there's something else we should change, please add to changelog.

**Comment by ngraef** [comment]
`md-tab-body` was renamed from `md-tab-template`, right?

**Pull request closed without merging**
