### PR TITLE
fix(autocomplete): placeholder and floating label behave as expected when both defined

### PR DESCRIPTION
**Pull request by vbanuelos**
Resolves https://github.com/angular/material/issues/5854

### CODE REVIEW

**Comment by vbanuelos** [comment]
I signed it!

**Comment by ThomasBurleson** [comment]
@robertmesserle - not sure I like this fix. Can you review.

**Comment by robertmesserle** [comment]
@ThomasBurleson This doesn't seem to work for me with both floating label and placeholder:

image

**Comment by vbanuelos** [comment]
@robertmesserle -- I tested by building up the live docs, and got the below. 

image

**Comment by ThomasBurleson** [comment]
@robertmesserle - ping.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Pull request closed without merging**
