### PR TITLE
update(docs): Docs website screenshot updated

### PR DESCRIPTION
**Pull request by mprentic-harris**
Trying again to see if the googlebot is happy with our CLA (signed by Harris Corporation).

### CODE REVIEW

**Comment by mprentic-harris** [comment]
I signed it!

**Comment by ThomasBurleson** [comment]
Is this a dummy PR that I should close ?

**Comment by mprentic-harris** [comment]
@ThomasBurleson the change is actually useful, so it could be merged. But the main purpose of it is to verify the CLA for Harris Corporation. I walked our contracts officer through it step by step in person today, so it should be working. I can't tell from this PR though whether or not it is indeed working since the google/cla check doesn't appear to be here in the list of checks.

Should I submit another PR to test it?

**Comment by mprentic-harris** [comment]
Updated PR opened with 0.11.0 screenshot and latest CLA submission in #4805.

**Pull request closed without merging**
