### PR TITLE
feat(datePicker): Add a configuration option for the debounce interval.

### LINKED ISSUE #8905: datePicker: model isn't updated until 500ms has passed since the last edit
**Actual Behavior**:
 -  `What is the issue?` *

My setup: I have a datePicker in a dialog, and when the dialog closes, I try to submit the data from the datePicker to my server.

If a user enters data into the datePicker and closes the dialog in less than 500ms, stale or otherwise invalid data gets sent to the server, because datePicker hasn't updated my model.

The general problem, I think, is that the debouncing in datePicker is too aggressive, and the datePicker component provides no way to force it to sync with the model. You're just stuck waiting for 500ms.

 -  `What is the expected behavior?`

I think it's reasonable to sync to the model on blur, because the blur event is a good indication that the user has finished entering data into the input field.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

You can see the impact of the 500ms delay on the Datepicker demo at https://material.angularjs.org/latest/demo/datepicker :

1) Put your cursor in the textbox under "Standard date-picker"
2) Quickly enter a new date and press tab
3) Note that it takes 500ms before the other date pickers are synced with the first one

**Angular Versions**: *
 -  `Angular Version:`
1.5

 -  `Angular Material Version:`
Noted on 1.0.9

**Additional Information**:
 -  `Browser Type: *`
Chrome

 -  `Browser Version: *`
51.0.2704.106 (64-bit)

 -  `OS: *`
Ubuntu

 -  `Stack Traces:`
N/A

### PR DESCRIPTION
**Pull request by mkowalchuk**
Fixes #8905

### CODE REVIEW

**Comment by crisbeto** [comment]
LGTM @ThomasBurleson.

**Comment by clshortfuse** [comment]
Functionality-wise, it looks good. My only concern is the inconsistency of the variable name with other elements. If I'm not mistaken, mdAutocomplete has something similar, but there it's called ‘wait‘.

**Comment by crisbeto** [comment]
The option in autocomplete is called `delay`, but I think it's different. The one in autocomplete seems to be the delay before results start showing up, the changes in this PR are for the debounce period before the model is updated.

**Comment by clshortfuse** [comment]
👍

**Pull request closed without merging**
