### PR TITLE
chore(tests): remove ddescribe()

### PR DESCRIPTION
**Pull request by caitp**
This was preventing tests from running, oops!

### CODE REVIEW

**Comment by caitp** [comment]
@gkalpak there are some failing tests though, that's not very good. Are you an owner/collaborator on this repo? We should get this reviewed and landed to prevent similar mistakes in the future

**Comment by ThomasBurleson** [comment]
@caitp - I am the team lead... best to escalate to me or @jelbourn.

**Comment by ThomasBurleson** [comment]
I just committed fixes to remove the `ddescribe`

**Comment by caitp** [comment]
I saw. There's a second (now only) commit in this CL which adds a check for ddescribe/iit to prevent it from sneaking in in the future

**Comment by ThomasBurleson** [comment]
@caitp - I like these changes. THANK you!

**Comment by ThomasBurleson** [comment]
@caitp - this stuff rocks!

**Pull request closed without merging**
