### PR TITLE
Update swipe.js

### PR DESCRIPTION
**Pull request by stewones**
annotate $parse DI for swipe directives

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@stewones - we use [ng-annotate](https://www.npmjs.com/package/gulp-ng-annotate) to prepare build the DI annotations at build time.

**Comment by ThomasBurleson** [comment]
@stewones - nice catch... I do not believe that ng-annotate would catch/work for this construction.

**Comment by ThomasBurleson** [comment]
@robertmesserle - if this is missing from the build for 0.7.1, will that affect internal users?

**Comment by ThomasBurleson** [comment]
@stewones - please sign the required CLA.

**Comment by stewones** [comment]
@ThomasBurleson - thx, i am trying to run here with ng-annotate 0.3.6. CLA already signed, what i have to do ?

**Comment by stewones** [comment]
@ThomasBurleson sounds good

**Comment by robertmesserle** [comment]
@ThomasBurleson Yea, I think we definitely want this internally.

**Comment by ThomasBurleson** [comment]
@stewones  -see https://github.com/angular/material/commit/22040c77b4f82dd9845ad6bcfab9ab62a534170c

**Comment by ThomasBurleson** [comment]
Fixed and committed to master. Thx

-- Thomas Burleson

**Comment by stewones** [comment]
@ThomasBurleson - <3 @ngInject. not know it was possible to do this way.
cya

**Pull request closed without merging**
