### PR TITLE
fix(radio): radio buttons cause errors in IE11

### PR DESCRIPTION
**Pull request by FreedCapybara**
## PR Checklist
Please check your PR fulfills the following requirements:
- [x] The commit message follows [our guidelines](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-commit-message-format)
- [x] Tests for the changes have been added or this is not a bug fix / enhancement
- [x] Docs have been added, updated, or were not required

## PR Type
What kind of change does this PR introduce?

```
[ x ] Bugfix
[ ] Enhancement
[ ] Documentation content changes
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Radio buttons do not work in IE11. This occurs on the [demo page](https://material.angularjs.org/latest/demo/radioButton).

On a page with `md-radio-button`, the error `TypeError: Argument not optional` appears in the console many times:
image

Fixes #

Defining the `entityReferenceExpansion` parameter ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/createTreeWalker)) removes the error and restores functionality.

## What is the new behavior?
In IE11, an error does not appear in the browser console and `md-radio-button` directives function correctly.

## Does this PR introduce a breaking change?
```
[ ] Yes
[ x ] No
```

## Other information

This can be verified in the browser console:
```js
document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, null); // produces an error in IE11
document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, null, false); // does not produce an error in IE11
```

### CODE REVIEW

**Comment by FreedCapybara** [comment]
It appears this is how it used to be, but was removed here https://github.com/angular/material/commit/5c455d30b8bcf4902add2c1ed0a6e9216147b43c

**Review by Splaktar — APPROVED** [review]
This was removed because that argument is now deprecated, but it looks like IE doesn't have the new API (figures). Thank you for the PR!

**Comment by Splaktar** [comment]
One more note, it looks like [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/createTreeWalker) isn't quite accurate on the IE support for `entityReferenceExpansion` being optional. It mentions that "whatToShow and filter optional" is not supported in IE, but it doesn't say that `entityReferenceExpansion` being optional is also not supported in IE.

I've submitted some feedback on this to MDN.

**Review by mmalerba — APPROVED** [review]
LGTM

**Comment by samal-rasmussen** [comment]
Oh man. Thaks for this. I could really use a build with this fix 🚢

**Pull request merged**
