### PR TITLE
fix(radiobutton,demoMultiColumn):  Index-1

### PR DESCRIPTION
**Pull request by moiltee**
The index is about one too big.

Bad index in radio button demo #5250.

### CODE REVIEW

**Comment by moiltee** [comment]
The change has been tested with a AngScope Firefox extension by changing value of the index manually in debugger. Could somebody accept this?

**Comment by moiltee** [comment]
I signed it!

**Comment by AbdelkaderBah** [comment]
Hi I think their's a same error here: https://material.angularjs.org/HEAD/demo/radioButton 
please fix it

**Comment by tihuan** [comment]
I was going to submit a PR for the same fix. Is this ready to merge :sunglasses:?

**Comment by moiltee** [comment]
Please submit your PR. I will close this one.

**Comment by tihuan** [comment]
Hey @moiltee! Just created a PR :) Thanks a lot! :+1: :tada:

**Pull request closed without merging**
