### PR TITLE
rtl problem when upgrade from rc4 to rc5

### PR DESCRIPTION
**Pull request by eqbalsajadi**
Before upgrade, everything was OK:
image

After that:
image

### CODE REVIEW

**Comment by DevVersion** [comment]
Hello,

What is the purpose of this PR? You like to merge the Change-Log and the Version'ing into `master`

**Comment by eqbalsajadi** [comment]
No, I just found a bug in rc5

**Comment by DevVersion** [comment]
Then you should close that Pull Request and create an Issue.

**Comment by eqbalsajadi** [comment]
Thank you :)

**Pull request closed without merging**
