### PR TITLE
fix secondary placeholder problem in chips

### PR DESCRIPTION
**Pull request by dbwhddn10**

### CODE REVIEW

**Comment by topherfangio** [comment]
I need to dig into this a bit further before we can review it.

@dbwhddn10 Can you provide any additional info as to what this fixes? Ideally a description, test case and an issue # would be fantastic!

**Comment by ericgundrum** [comment]
@topherfangio, I have unit tests demonstrating issues #2770 and #4476. (Currently there are no unit tests for the _placeholder_ feature of `mdChips` input.) If you like, I can offer PRs with those tests and the related fix. (The fix is a single line.) Or, I could just post the tests here or in one of the issue threads. Just let me know what your prefer.

I wrote a test to match the issue PR a5dba2a27e44ee04ad47f1cf0ef4a9e4212eef79 is trying to fix. However, there is much other `mdChips` code that fails to check if the `ngModel` is defined. There seems to be an inherent assumption that `ngModel` is defined or that catastrophic failure is preferred when it isn't. It may be better to separate this issue and PR from issues #2770 and #4476.

**Comment by EladBezalel** [comment]
@ericgundrum thanks.
@dbwhddn10 can you please rebase?
@topherfangio can you please investigate? :)

**Comment by topherfangio** [comment]
I'm going to go ahead and close this in favor of #6175 since it does the NPE check only and #6535 has already been merged.

**Pull request closed without merging**
