### PR TITLE
Feature tabs icons

### PR DESCRIPTION
**Pull request by fredmorin**
Added support for icons in the tabs component.
Added a demo for icons in the tabs component.

### CODE REVIEW

**Comment by fredmorin** [comment]
I signed it!

**Comment by ThomasBurleson** [comment]
@EladBezalel, @clshortfuse - please review and test.

**Comment by EladBezalel** [comment]
@fredmorin it seems to be [working](http://codepen.io/EladBezalel/pen/rrNXPA), next time file an issue and in case it's really needed and you will, we'd ask you to create a PR.

Thanks for the work though.

**Comment by ThomasBurleson** [comment]
@fredmorin - Thank you for this PR. Is there specific functionality missing or features not working? if so, please provide an issue with a CodePen demonstrating the use case(s).

**Comment by fredmorin** [comment]
I don't understand what is the plan with feature. Can I expect this feature to be part of the 1.1.2 release? Should I open an issue?

**Comment by ThomasBurleson** [comment]
@fredmorin - @EladBezalel provided a [CodePen Demo](http://codepen.io/EladBezalel/pen/rrNXPA) showing that icons are showing in the Tab buttons. If this is not working for you, please open a new issue WITH a CodePen demonstrating the issue. And reference this PR # in your new issue.

**Comment by fredmorin** [comment]
@EladBezalel demonstrates one issue with the icon color, different from text color when the tab is not active.

**Comment by ThomasBurleson** [comment]
@EladBezalel - plz open an issue for ^.

**Pull request closed without merging**
