### PR TITLE
feat(mdGesture): allow to change maxClickDistance through $mdGestureProvider.setMaxClickDistance

### LINKED ISSUE #10492: mdGesture: allow to change default maxClickDistance value in gesture provider
I'm having some issues with Samsung Galaxy Tab touch screen and mdGesture; mdGesture is often "ignoring" taps. I've found out that changing maxClickDistance to something about 20px makes it behaving much better.
 
I'll make a PR with maxClickDistance setting exposed on mdGesture provider.

### PR DESCRIPTION
**Pull request by mprokopowicz**
on some touch devices tap is often lost due to small finger movements

fixes #10492

### CODE REVIEW

**Comment by mprokopowicz** [comment]
Can someone of maintarners explain me why the build failed? Tests were pasing on my local machine.

**Comment by EladBezalel** [comment]
@DevVersion any idea?

**Comment by DevVersion** [comment]
@EladBezalel Looks like `code.angularjs.org` was at this time down. Restarted the builds and it seems to work.

**Comment by mprokopowicz** [comment]
Any chances to merge it before 1.1.4?

**Pull request merged**
