### PR TITLE
refactor(bottomSheet,dialog,list,select,input,menu,menuBar): denote private classes with _md prfix

### PR DESCRIPTION
**Pull request by rschmukler**
**Note**: This commit will break input until it has been updated with private classes. I modified some of the classes as they interact with `md-select`. Presumably @topherfangio changes will result in the same changes as I made resulting in full compatibility between select and input.

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@jelbourn - Can you review these to confirm these changes. The goal is to also use these changes as 'standards' for CSS changes in the other components.

**Comment by topherfangio** [comment]
@rschmukler Looks like we did make the same changes. Thanks for the heads-up.

LGTM

**Comment by jelbourn** [comment]
@rschmukler For all the classes that _aren't_ private, we're able to say that they won't see any major changes in the foreseeable future?

**Comment by ThomasBurleson** [comment]
@rschmukler - ping for @jelbourn question.

**Comment by ThomasBurleson** [comment]
Duplicate. See aggregation into PR #7248.

**Pull request closed without merging**
