### PR TITLE
fix(autoComplete): don't use $mdUtil.nextTick in handleHiddenChange

### LINKED ISSUE #9318: When md-autocomplete is removed (by ng-if) the md-scroll-mask is not removed.
When `md-autocomplete` is removed (by `ng-if`) the `md-scroll-mask` is not removed.
@cah-alexsukhodolsky tried to fix it in 042086f34f4d9bb54228dbc4968b520228f73de0, but he didn't cover the scenario when `md-autocomplete` is removed immediately after an item is chosen.
The `$mdUtil.nextTick` doesn't call the `$mdUtil.enableScrolling` (because the `$scope` is destroyed) and the `cleanup` function will not remove the `md-scroll-mask` (because the `ctrl.hidden` is true).

[CodePen Demo](http://codepen.io/leibale/pen/kXqbvR)

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.0-rc.5

### PR DESCRIPTION
**Pull request by leibale**
#9318

### CODE REVIEW

**Comment by gkorland** [comment]
+1

**Comment by DevVersion** [comment]
I will take a look at the source soon, but for the beginning you could change your commit description and PR description to follow the guidelines.

> https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md

**Comment by leibale** [comment]
I cant add a break in the commit message (it's a input, not a textarea).
Also i can't read the pull request guidelines because the link is broken (https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#submitting-pull-requests)..

**Comment by DevVersion** [comment]
@leibale Normally it should be a textarea. Try using `git commit --amend` to get a full view of the commit editor.

Also the commit message is still not valid. 
> https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-commit-message-format

**Comment by leibale** [comment]
@DevVersion now it's ok?

**Comment by leibale** [comment]
@DevVersion ..? :(
it's really important to me..

**Comment by DevVersion** [comment]
@leibale I'm sorry I didn't have a change to take a look at it the last days. I'm going to take a look at it today.

**Comment by leibale** [comment]
@DevVersion thanks

**Comment by DevVersion** [comment]
@ThomasBurleson Just tried it out locally and it seems to work as expected. LGTM.

**Pull request merged**
