### PR TITLE
fix(datePicker): ensure one is able to override default sass variables values

### PR DESCRIPTION
**Pull request by sryzycki**

### CODE REVIEW

**Comment by sryzycki** [comment]
I signed it!

**Comment by DevVersion** [comment]
LGTM

**Comment by ThomasBurleson** [comment]
@jelbourn - I assume you had specific reasons why you used `!default`... so their removal would be problematic ?

**Comment by jelbourn** [comment]
LGTM. I just forgot to add `!default` when I wrote them.

**Pull request closed without merging**
