### PR TITLE
fix(layout): resolve issues with IE and calc() in flexbox

### LINKED ISSUE #6849: flex-33 and flex-66 use calc within a flexbox
According to http://caniuse.com/#search=calc calc is not properly supported within a flex box on IE 11. 3d6077b446b7c7831d4ec0d95a3250e9e4b59be0 uses calc() in this fashion.

### before the update (working)
http://codepen.io/mmaguigan-dti/pen/bEvLjj
### after the update (not working)
http://codepen.io/mmaguigan-dti/pen/EPEQQa

### PR DESCRIPTION
**Pull request by ThomasBurleson**
Fixes #6849.

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@topherfangio - can you review ?

**Comment by topherfangio** [comment]
@ThomasBurleson LGTM - Do you recall why you changed it to `calc` in the first place?

**Comment by ThomasBurleson** [comment]
@topherfangio - previously (1.0.2), the setting was

`css

**Comment by topherfangio** [comment]
Gotcha. Sounds good to me :-)

**Pull request closed without merging**
