### PR TITLE
update(commit_levels): fix minor typos

### PR DESCRIPTION
**Pull request by Splaktar**

### CODE REVIEW

**Comment by topherfangio** [comment]
@Splaktar I was planning to do this today, but since you've already grabbed it, would you mind taking a look at the links to each person? They seem to load the wrong URL.

**Comment by topherfangio** [comment]
Can you also rework line 41 a bit? It says "for minor changes" twice.

**Comment by Splaktar** [comment]
Will do!

**Comment by Splaktar** [comment]
@topherfangio done!

**Comment by topherfangio** [comment]
@Splaktar Thanks!

@ThomasBurleson LGTM :-)

**Comment by ThomasBurleson** [comment]
Closed with SHA 546eb84604ce512feae4249d5103654a56d4ea1b

**Pull request closed without merging**
