### PR TITLE
fix(layout): add missing flex layouts

### PR DESCRIPTION
**Pull request by mutoo**
I've made a complex responsive grid in my project, but it did work well with current build.

```
<div layout-xs="column" layout-gt-xs="row" layout-wrap>

      <!-- left -->
      <div flex-order-xs="2"
           flex-gt-xs="33"
           flex-gt-md="20"></div>

      <!-- middle -->
      <div flex-order-xs="1"
           flex-gt-xs="66"
           flex-gt-md="50"></div>

      <!-- right -->
      <div flex-order-xs="3"
           flex-gt-xs="66" flex-offset-gt-xs="33"
           flex-gt-md="30" flex-offset-gt-md="0"></div>
</div>
```

After some inspections, I found that some layout-flex combinations were missing. e.g. `layout-gt-xs-row > flex-gt-md-*`.

This patch will add those missing combinations, including:

```
.layout-gt-xs-(row|column)
  > .flex-gt-sm-*
  > .flex-gt-md-*
  > .flex-gt-lg-*

.layout-gt-sm-(row|column)
  > .flex-gt-md-*
  > .flex-gt-lg-*

.layout-gt-md-(row|column)
  > .flex-gt-lg-*
```

and rearrange the order of those selector to avoid overrides.

```
.layout-gt-md-(row|column)
  > .flex-gt-lg-5
  > .flex-gt-lg-10
  ...
  > .flex-gt-lg-30
  > .flex-gt-lg-33
  > .flex-gt-lg-35
  ...
  > .flex-gt-lg-65
  > .flex-gt-lg-66
  > .flex-gt-lg-70
  ...
```

### CODE REVIEW

**Comment by mutoo** [comment]
still have some problem with default layout.

need to lift default layout above all other layout-gt-*

```
.layout-(row|column)
  > .flex-gt-xs-*
  > .flex-gt-sm-*
  > .flex-gt-md-*
  > .flex-gt-lg-*

.layout-gt-*-(row/column)
  > ...
```

**Comment by ThomasBurleson** [comment]
@mutoo - please rebase and squash your commits.

**Comment by mutoo** [comment]
hi @ThomasBurleson , I'm really sorry to mess with this pull request. I never to the squash before, how could I fix that, or may I create another pull request?

**Comment by ThomasBurleson** [comment]
@mutoo - Here is what I would do.

*  Locally checkout the branch that you created as the source for `mutoo:patch-layouts`
*  Locally use `git rebase -i HEAD~4`, change the `pick` to `s` for the commits.
* Exit rebase (and save your changes)
* Confirm the history has squashed the commits desired
* Use `git push -f origin patch-layouts` to force push your branch to your origin fork
* You should see this PR auto-updated.

**Comment by mutoo** [comment]
@ThomasBurleson Thanks for your help! I just undeleted the branch and successfully squashed those commits, but this PR does not update.

here is the old commits' tree: https://github.com/mutoo/material/commits/d1cafef49469e6bf228f6e80b907e2fb774574e1

and the new one:
https://github.com/mutoo/material/commits/9bc5cf68acbc76a96356ef18f1fb18356cf52855

**Pull request closed without merging**
