### PR TITLE
update(docs): Fix autocomplete input-name example.

### PR DESCRIPTION
**Pull request by tuhoojabotti**
input-name is actually md-input-name

[Review on Reviewable](https://reviewable.io/reviews/angular/material/3437)

### CODE REVIEW

**Comment by wcjr** [comment]
just curious, why is this additional directive needed for "name"?

**Comment by tuhoojabotti** [comment]
I agree, I think it should work with just the standard `name` attribute.

**Comment by ThomasBurleson** [comment]
@tuhoojabotti - since you have presented this PR, can you plz add docs for:

*  md-input-name
*  md-input-minlength
*  md-input-maxlength

Thx.

**Comment by tuhoojabotti** [comment]
@ThomasBurleson Added notes about those attributes.

**Pull request closed without merging**
