### PR TITLE
Chore protractor tests

### PR DESCRIPTION
**Pull request by topherfangio**
In order to more fully test our components and their interactions amongst each other, add protractor tests for e2e testing.

Additionally, we may leverage this in the future to allow for screen difference testing.

### CODE REVIEW

**Comment by topherfangio** [comment]
@DevVersion Please review 😄

**Comment by parky128** [comment]
Hi there, I came across this PR when searching for references to Protractor in the repo as I have been having difficulties getting a set of e2e tests to run in a stable manner that involve interacting with Angular Material components on the page. 

Are there any plans to provide us with guides on how to best test AM components using protractor, and avoid the need for browser.sleep() calls

**Comment by Splaktar** [comment]
This would be really nice to get merged and should be possible since it has no chance of breaking any APIs, etc. Please rebase and we'll try to review and get this merged ASAP.

**Comment by topherfangio** [comment]
@Splaktar Hey man; I'm no longer on the Angular team as I have a new job. Additionally, I haven't even launched the project in like 6 months, so you'll need to see if someone else can rebase this :-)

Cheers!

**Comment by Splaktar** [comment]
We've migrated to CircleCI and most of this PR is set up for TravisCI.

Additionally
- we do not currently have the resources to write the actual Protractor e2e tests that this PR enables
- with LTS starting soon for this project, there isn't a lot of value to be had from e2e testing

Due to those factors, I'm going to close out this PR.

**Pull request closed without merging**
