### PR TITLE
fix(virtualRepeat, autoComplete): Recompute number of items after aut…

### PR DESCRIPTION
**Pull request by kseamon**
…o-(un)shrink.

### CODE REVIEW

**Comment by kseamon** [comment]
Fixes the remaining manifestation of #5606

**Comment by kseamon** [comment]
@jelbourn @robertmesserle @ThomasBurleson

**Comment by jelbourn** [comment]
LGTM

**Comment by jelbourn** [comment]
Closed via b19d5cb2f4eef0b992b4b5964b29c18d2bf8c40b

(I did it right away because I wanted to try out my new shortcut for merging PRs...)

**Pull request closed without merging**
