### PR TITLE
feat(datepicker): support custom-defined tabindex attributes

### LINKED ISSUE #8147: md-datepicker does not focus forward to generated input element
When tabbing through a form with custom-defined tabindex attributes, md-datepicker does not function as expected by selecting the internally-compiled input HTML element. Instead, the tabbing sets the focus the md-datepicker element itself, not the input field and neither does it focus forward to the input. The only way to input data into the date picker input field without clicking on the field is to cycle completely through the form, after which the datepicker input field is finally selected.

[I've made an example on codepen](http://codepen.io/mcdwight6/pen/oxymgx)
screen shot 2016-04-20 at 6 26 13 pm

### PR DESCRIPTION
**Pull request by mcdwight6**
Push tabindex from datepicker onto child input elem to preserve expected UX plus a few typos
closes #8147

### CODE REVIEW

**Comment by mcdwight6** [comment]
Seems this commit didn't quite work. Not sure what the errors mean though. Was trying to implement a similar solution to the one closing issue #2113

**Comment by crisbeto** [comment]
The CI issues are because of some syntax errors:

```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  SyntaxError: Unexpected token ':'
  at /home/travis/build/angular/material/src/components/datepicker/datePicker.js:89
PhantomJS 2.1.1 (Linux 0.0.0): Executed 0 of 0 ERROR (0.294 secs / 0 secs)
Firefox 31.0.0 (Linux 0.0.0) ERROR
  SyntaxError: missing ; before statement
  at /home/travis/build/angular/material/src/components/datepicker/datePicker.js:89
Firefox 31.0.0 (Linux 0.0.0): Executed 0 of 0 ERROR (0.539 secs / 0 secs)
[03:52:16] Karma exited with the following exit code: 1
```

**Comment by topherfangio** [comment]
@mcdwight6 My guess would be that it has to do with your ternary operator on [line 64](https://github.com/angular/material/pull/8150/files#diff-f689e6a52f85d0d651bffa590b2ecdddR64) of the `datepicker.js`.

Perhaps our build system on the CI doesn't like that syntax.

I tried running this locally, but we've apparently changed the directory structure recently and moved most of the code into the [datepickerDirective.js](https://github.com/angular/material/blob/master/src/components/datepicker/js/datepickerDirective.js) file.

You think you could rebase and check the syntax in your conditional statement? You might be able to use parentheses around it to make it pass. If you can rebase, though, I can take a look on my local machine and help you out.

**Comment by crisbeto** [comment]
@mcdwight6 it's been a while since you opened this. It seems like your PR has some merge conflicts. Can you resolve them and fix the CI failures?

**Comment by crisbeto** [comment]
I'll close the PR since there's been no reply for a while now, the tests are failing and it needs a rebase. I'll try to resolve #8147 in a separate PR.

**Pull request closed without merging**
