### PR TITLE
update(panel): Increase animation open/close speed.

### PR DESCRIPTION
**Pull request by ErinCoughlan**
@ThomasBurleson Please review.

@EladBezalel Please test this on your computer. :smile:

### CODE REVIEW

**Comment by EladBezalel** [comment]
@ErinCoughlan lgtm

**Comment by ThomasBurleson** [comment]
rejected with emphasis. 💩

**Comment by ErinCoughlan** [comment]
It works on my computer!

**Comment by gmoothart** [comment]
works on my machine

**Pull request closed without merging**
