### PR TITLE
Fix scss to centered close button of chips

### PR DESCRIPTION
**Pull request by Grmiade**
With this changements, chips close button is now centered vertically with Safari and Chrome browser.

### CODE REVIEW

**Comment by Grmiade** [comment]
I signed it!

**Comment by topherfangio** [comment]
Thanks for the PR! However, I believe I already fixed this issue a few days ago. When I test out your PR against the latest master code, it doesn't appear to move the close button at all, but it does cause some alignment issues with the static chips.

Can you double-check that this is still a valid PR?

**Comment by Grmiade** [comment]
Indeed, this change is not necessary on latest master branch :)

**Comment by topherfangio** [comment]
Okay, thanks so much!

We definitely appreciate PRs, so please feel free to continue submitting them :-)

**Pull request closed without merging**
