### PR TITLE
feat(dataTable): implementing mdDataTable

### PR DESCRIPTION
**Pull request by daniel-nagy**
Initial Implementation of the Material Design Data Table.

**FYI**: This is currently a Work in Progress.

### CODE REVIEW

**Comment by gpopovic** [comment]
Looking forward to removing md-data-table dependency :)

**Comment by DevVersion** [comment]
@googlebot It's fine. I confirm, that I'm okay with these commits being contributed.

FYI: Interesting, how the Bot recognizes texts.

**Comment by daniel-nagy** [comment]
> please add them to this pull request and have them confirm that they're okay with these commits being contributed to Google

Would be nice if @googlebot explained how to do this.

**Comment by DevVersion** [comment]
@daniel-nagy Haha. Definitely agree :smile: 

@googlebot I confirm!

**Comment by gpopovic** [comment]
Any news on this one?

**Pull request closed without merging**
