### PR TITLE
fix(datepicker): Fix validation in IE.

### LINKED ISSUE #9994: datepicker: validation behaves differently in IE
**Actual Behavior**:
You can test it here in angular material demos for IE and Chrome:
https://material.angularjs.org/1.1.1/demo/datepicker
 The issue is when you input an invalid value in the date picker in IE with ngMessages, it says "Only Weekends are allowed", then when you add a letter in the input, it doesn't validate it (for example 11/9/2016 and after that input a letter, 11/9/2016t). I was expecting to have this message showed "The entered value is not a date!" but it didn't. It wasn't happening when I was using Angular Material 1.0.8.
In Chrome, it validates correctly so if you add a letter in datepicker input, it says "The entered value is not a date!". This only became an issue from angular material 1.1.0 in IE.

** steps to reproduce the issue**
 -  https://material.angularjs.org/1.1.1/demo/datepicker
 -  `Details:` adding a letter in input "With ngMessages", the validation message stays "Only Weekends are allowed" instead of "The entered value is not a date!".

### PR DESCRIPTION
**Pull request by topherfangio**
Adds in validation for the input as a last check as IE interpreted the date '11/14/2016d' as valid which is incorrect.

_Note: This PR supersedes #10015 by adding a test._

Fixes #9994. Closes #10015.

### CODE REVIEW

**Comment by richardhughes** [comment]
Hey @topherfangio, Looks good to me, I've just noticed that Google Bot has put a message on this to get confirmation.

I couldn't get the test runner to work in the end, but that was down to my old development machine.

**Comment by topherfangio** [comment]
@richardhughes Thanks! I've marked it as `cla: yes` since you approved it. Thomas should review it when he has a chance, but he and much of the team is at ngConf right now, so it will likely happen after they return.

**Comment by ThomasBurleson** [comment]
@topherfangio - can you squash your commits.

**Comment by Splaktar** [comment]
Closing this in favor of https://github.com/angular/material/pull/11110 since the request to squash commits was not resolved.

**Pull request closed without merging**
