### PR TITLE
style(list): aligned list with material spec

### LINKED ISSUE #6862: md-list-item md-divider[md-inset]
According to the specifications, 
https://www.google.com/design/spec/components/lists.html#lists-specs

the left distance should be 72px instead of 96px.

```css 
md-list-item md-divider[md-inset] {
    left: 72px;
    width: calc(100% - 72px);
    margin: 0;
}
```

Thank you.

### PR DESCRIPTION
**Pull request by EladBezalel**
* Fixed incorrect margins
 * long-text margin fix
 * avatar position and size
* Added dense mode - https://www.google.com/design/spec/components/lists.html#lists-specs

fixes #6862 and #6783

> #breaking

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@topherfangio - can you review/test this.

**Comment by topherfangio** [comment]
@EladBezalel Everything looks good to me, but can you amend the commit message to include a note about the margin change so users will be aware of it?

**Comment by topherfangio** [comment]
@EladBezalel Once the commit message is updated, you can feel free to mark it as Needs Merge and assign it to Thomas.

**Comment by ThomasBurleson** [comment]
:+1:

**Pull request closed without merging**
