### PR TITLE
docs(input): fix typo in demo

### LINKED ISSUE #2556: update(docs): md-input typo correction
In the md-input error demo:

$5,000 an hour? That's a little ridiculous. I doubt **event** Bill Clinton could afford that

Should be `even`

### PR DESCRIPTION
**Pull request by robertbaker**
Fixes a typo in the input demo.

fixes #2556

### CODE REVIEW

**Comment by robertbaker** [comment]
I signed it!

**Comment by topherfangio** [comment]
Hi @robertbaker! Thanks so much for the PR!

When submitting, please make sure to follow the [commit comment guidelines](https://github.com/angular/material/blob/master/docs/guides/CONTRIBUTING.md#commit-message-format) as this gets copied to the PR and will help us better understand it's purpose.

As an example, I have updated this PR's title/description to match.

Also, if it fixes an existing issue, please include it as I have above so that GitHub can do some spiffy automation for us :-)

**Comment by robertbaker** [comment]
@topherfangio will do next time. Not sure how I can change my commit message.

**Comment by EladBezalel** [comment]
@robertbaker please rebase

**Pull request closed without merging**
