### PR TITLE
Fixes for safari

### PR DESCRIPTION
**Pull request by JulianWielga**
safari has problem with big body of <style> tag created by js

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@JulianWielga 

- Please squash your commits
- Please rebase from current master and test
- Please provide a CodePen or Plunkr that demonstrates this issue and PR fixes.

**Comment by ilanbiala** [comment]
@JulianWielga why was this PR closed?

**Comment by JulianWielga** [comment]
@ilanbiala not noticed, probably by mistake

**Comment by JulianWielga** [comment]
rebased

links to simple demos
http://codepen.io/ThomasBurleson/pen/xbYxrX - grid not working in safari
http://codepen.io/JulianWielga/pen/JoVrpQ - grid working with my fix

http://codepen.io/JulianWielga/pen/rabGdo - themes not working in safari
http://codepen.io/JulianWielga/pen/yyrzjq - working themes

**Comment by ThomasBurleson** [comment]
@JulianWielga - fast response  :+1:  Thx

**Comment by ecunal** [comment]
Any updates on this matter?

@JulianWielga I got your changes and built angular-material.js and css locally, however our page with a `md-grid-list` is still broken as before in Safari. I also tried to get the angular-material.js library you built and used in the codepen demos, but still no luck. Are there any other changes that I must apply?

**Pull request closed without merging**
