### PR TITLE
fix(autocomplete): improve dropdown options bottom space calculation

### LINKED ISSUE #11661: autocomplete: calculating space for options panel
https://github.com/angular/material/blob/e6f4057bb5e4a50c4d3aeffffd38518ff393e1ba/src/components/autocomplete/js/autocompleteController.js#L164

When calculating the space needed for the autocomplete options, the calculation is not taking into account the shifted body positioning, when in the context of an mdDialog. This results in either the options going the wrong direction or the container being too narrow.

https://codepen.io/anon/pen/QoKOPP

### PR DESCRIPTION
**Pull request by nathanael-bice**
If the body of the page has been shifted, such as due to an open dialog, the autocomplete options should know about it with regards to positioning.

Fixes #11661

## PR Checklist
Please check that your PR fulfills the following requirements:
- [x] The commit message follows [our guidelines](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-commit-message-format)
- [x] Tests for the changes have been added or this is not a bug fix / enhancement
- [x] Docs have been added, updated, or were not required

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Enhancement
[ ] Documentation content changes
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: 

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by nathanael-bice** [comment]
I signed it

**Comment by nathanael-bice** [comment]
I signed it

**Comment by Splaktar** [comment]
Thank you for submitting this PR and the associated fix **with tests**!

Is possible, please update your commit message to [follow the guidelines](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-commit-message-format) as that is required for your changelog generation. 

I just posted a PR (https://github.com/angular/material/pull/11670) that addresses this issue along with some others. I'm going to take another look at it tomorrow and compare our approaches.

**Comment by nathanael-bice** [comment]
The change in #11670 does seem to be a more complete solution to the issue, compared to my fix. This change is no longer required with that change.

**Comment by Splaktar** [comment]
OK, thank you for looking into this issue!

**Pull request closed without merging**
