### PR TITLE
fix(utils): isNumPadKey should allow zero on numpad

### PR DESCRIPTION
**Pull request by Zangalot**
[https://github.com/angular/material/issues/10593]

### CODE REVIEW

**Comment by Zangalot** [comment]
I signed it!

**Comment by ThomasBurleson** [comment]
Refs Issue #10593

**Comment by ThomasBurleson** [comment]
@Zangalot - please squash your commits and sign the CLA.

**Comment by ThomasBurleson** [comment]
Closing as invalid PR.

**Pull request closed without merging**
