### PR TITLE
feat(mixin) Improved `input-placeholder-color` mixin

### PR DESCRIPTION
**Pull request by IPRIT**
Allows to set style for input state selectors (e.g. :hover, :active, :focus)

Examples:
  
```scss
@include input-placeholder-color(#faf);
```

```scss
@include input-placeholder-color(#faf, (hover: #ff0));
```

```scss
@include input-placeholder-color(#faf, (hover: #ff0, active: #0ff)) {
  transition: all .2s ease-in-out;
}
```

### CODE REVIEW

**Comment by DevVersion** [comment]
Where will be that functionality used? Seems like it's just improving the mixin without any required usage?

**Comment by IPRIT** [comment]
@DevVersion, I can offer this effect for focused input. But I need help to finish this.

**Comment by clshortfuse** [comment]
I'm not sure I see the reason for this. Also, `md-input-focused` is where the label gets its color on focus. Users can already override that with custom CSS.

But it seems to want to color the placeholder/hint text on focus. I'm not sure that is part of Material Design spec. Generally, we ask users to file an issue first before proposing changes so we can investigate their validity and best course of action.

**Comment by DevVersion** [comment]
Correct. I kept it open to get the reason for this change, but since you said this requires more work / help and it's kind of an unused change, you should file an issue first.

Thanks for the contribution through.

**Pull request closed without merging**
