### PR TITLE
feat(core): added the initial benchpress structure

### PR DESCRIPTION
**Pull request by cssensei**
Just the starting structure for testing the entire framework as proposed (in #5358) and discussed in the design doc with @jelbourn & @ThomasBurleson.

It's a WIP and I would like to push more changes to it (include it in the travis build plan, define a proper benchmark folder structure for every component, define and implement a full test plan for angular material design) after the initial review.

### CODE REVIEW

**Comment by jelbourn** [comment]
Is this runnable? I.e., can I pull down this change and run something and get some benchpress output?

**Comment by cssensei** [comment]
@jelbourn yes it's runnable. How to instructions are in [BENCHMARKS.MD](benchmarks/BENCHMARKS.MD)

**Comment by jelbourn** [comment]
@cssensei Sorry for the delay, we're trying to get a ton of bugs fixed for the 1.0 release soon. I'll get back to this as soon as that's done.

**Comment by cssensei** [comment]
@jelbourn no problem, don't worry! I'm working on updating our spec document with some proposals for the bechmarking strategies that we could adopt. I'll also check if I can take on some fixes for 1.0 release

**Comment by ThomasBurleson** [comment]
Closing this as outdated. Will not merge. Benchmark support will be integrated into the Material2 processes.

**Pull request closed without merging**
