### PR TITLE
added landscape and portrait queries

### PR DESCRIPTION
**Pull request by davidenke**
As mentioned by @ThomasBurleson in #8609 the landscape and portrait media queries have been added.

### CODE REVIEW

**Comment by davidenke** [comment]
I signed it!

**Comment by DevVersion** [comment]
We should probably support these new breakpoints in the layout engine as well.
> https://github.com/angular/material/blob/master/src/core/services/layout/layout.js#L80

So you can use for example:
```html
<div layout-landscape="row">
```

**Comment by ThomasBurleson** [comment]
@daniel-nagy My only concern here is the potential large increase in generated Layout CSS. 

> I will investigate.

**Comment by ThomasBurleson** [comment]
@davidenke - So my worry was misplaced. Your change is only for the `$mdMedia` service and does not impact the Layout API nor its generated Layout CSS.

**Comment by ThomasBurleson** [comment]
@DevVersion - perhaps we could just support the `layout-landscape` and `layout-portrait` features without any other enhancements ?

**Comment by DevVersion** [comment]
@ThomasBurleson I agree, that would keep the CSS size small and would be still super useful enhancement.

**Pull request closed without merging**
