### PR TITLE
fix(radioButton): set checked based on object equality if viewValue is an object

### PR DESCRIPTION
**Pull request by j-hogue**
Fix mdRadioButtonDirective.render to set checked based on object equality if viewValue is object

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@j-hogue  Please provide unit tests to verify these changes. Afterwards, we will review and (if passed) merge to master.

**Comment by ThomasBurleson** [comment]
@j-hogue - please rebase your changes and squash your commits.

**Comment by j-hogue** [comment]
@ThomasBurleson done.

**Comment by Splaktar** [comment]
Moving to backlog as unit tests have not been provided for this change.

**Comment by Splaktar** [comment]
I'm going to close this as there does not appear to be significant interest in getting this enhancement merged in.

**Pull request closed without merging**
