### PR TITLE
fix(md-slider): set step property relative to min

### LINKED ISSUE #4385: md-slider step should be relative to min property
`step` property should be relative to `min`, see: 
http://codepen.io/karolkochan/pen/gaOMjX 

Slider settings:
min: 15
max: 185
step: 10

Slider jumps through 20, 30, 40, 50... instead of 15, 25, 35, 45... and so on.

### PR DESCRIPTION
**Pull request by karolkochan**
Closes #4385

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@CarmenPopoviciu - care to review this one?

**Comment by ThomasBurleson** [comment]
@CarmenPopoviciu - can you review this ?

**Comment by CarmenPopoviciu** [comment]
@ThomasBurleson definitely. I'll have it done today

**Comment by CarmenPopoviciu** [comment]
@ThomasBurleson this looks OK from my side, so I think we can merge it away

**Comment by ThomasBurleson** [comment]
@karolkochan - please rebase and update this PR.

**Comment by karolkochan** [comment]
@ThomasBurleson - done

**Pull request closed without merging**
