### PR TITLE
feat(layout): allow flex-order to be negative

### LINKED ISSUE #4482: Allow flex-order to be negative
According to [CSS Flexible Box Layout Module Level 1](http://www.w3.org/TR/css3-flexbox/#order-property) and [CSS Values and Units Module Level 3](http://www.w3.org/TR/css-values/#integers), the `order` property can be negative, -9 to -1, as well as positive, 1 to 9, and zero.

With this feature, developers can use positive and negative flex-orders for general (search results) and special (ads) flex items respectively.

Here's a demo based on v0.11.0-rc2 with a simple patch for this feature request:
http://codepen.io/flowersinthesand/pen/ojgrmj

### PR DESCRIPTION
**Pull request by flowersinthesand**
Fixes #4482.

### CODE REVIEW

**Comment by flowersinthesand** [comment]
Please review this pull request first and let me know if it looks good to you. If so, I'll sign up CLA. (Though, to be honest, I don't understand why I have to fill in country and phone number just to sign up CLA.)

**Comment by ThomasBurleson** [comment]
All contributors **must** sign the CLA to contribute Pull Requests.

**Comment by ThomasBurleson** [comment]
> I am manually merging this PR into a work-in-progress; due to patch conflicts.

**Comment by flowersinthesand** [comment]
Well.. fair enough, I'll do that.

**Comment by flowersinthesand** [comment]
I signed it. The master branch has no conflicts. Which branch will you use?

**Pull request closed without merging**
