### PR TITLE
fix(tabs): unable to swipe to scroll on touch IE

### LINKED ISSUE #10526: swipe(left/right): disables default swipe-down behavior in IE on WIN8 RT tablet
**Actual Behavior**:
 -  `What is the issue?` 
when md-tab-content has defined md-swipe-left and right to swipe the tabs, swipe down gesture made on this md-tab-content element is not working to scroll down the page
 -  `What is the expected behavior?
when md-tab-content has defined md-swipe-left and right to swipe the tabs, swipe down gesture made on this md-tab-content element should still work as default behavior when you swipe down to scroll down the page

**AngularJS Versions**: *
 -  `AngularJS Version:` 
v1.5.5
 -  `AngularJS Material Version:`
v1.1.0

**Additional Information**:
 -  `Browser Type: Internet Explorer
 -  `Browser Version: 10
 -  `OS: WIN8 rt on Samsung ATIV

Tested on another tablets, Android/iOS, and working fine

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes not being to swipe down to scroll in IE on touch devices.

Fixes #10526.

### CODE REVIEW

**Comment by mmalerba** [comment]
this causes a couple of screenshot diffs in g3

**Comment by Splaktar** [comment]
We need more information about the screenshot diff failures in order to move forward on this. A CodePen demo would be ideal.

**Comment by Splaktar** [comment]
Feedback on the presubmit failures: this PR "seems to introduce a bunch of scroll bars to apps that didn't have them before, seems to be mainly on mobile devices".

**Comment by Splaktar** [comment]
This doesn't appear to be needed after https://github.com/angular/material/pull/10455 was merged.

**Pull request closed without merging**
