### PR TITLE
fix(select): text-align:end is not supported in IE

### LINKED ISSUE #2213: md-select ▼ displaying underneath text in IE10
For IE10, the arrow, ▼, that appears to the right in browsers other than IE10 for md-select appears under the text in IE10.  This can be seen at https://material.angularjs.org/#/demo/material.components.select.

### PR DESCRIPTION
**Pull request by prestonvanloon**
`text-align: end` is not supported by some browsers. This can cause improper positioning of the md-select-icon

https://developer.mozilla.org/en-US/docs/Web/CSS/text-align

Fixes #2213

### CODE REVIEW

**Comment by clshortfuse** [comment]
Using right instead of end would conflict with right-to-left languages.

**Comment by prestonvanloon** [comment]
Good point, I will update

**Comment by ThomasBurleson** [comment]
@prestonvanloon - you should probably change this also;

`@include rtl(align-items, flex-end, flex-start);`

**Comment by prestonvanloon** [comment]
@ThomasBurleson - agreed

**Comment by prestonvanloon** [comment]
I think this has been resolved elsewhere

**Comment by Splaktar** [comment]
This was tweaked in https://github.com/angular/material/commit/70c0c6e80391026c09785c4703becb34a690ba7b, but that only made the carrot not show up under the text. It didn't fix the left-to-right alignment.

This is still a problem as noted in https://github.com/angular/material/issues/10714.

**Comment by clshortfuse** [comment]
It's a bit confusing, but it seems what happened was that this PR was closed by the creator and never merged. It would have solved the issue properly. The second commit that came later in August was a partial fix, but that was a direct commit without a PR and wasn't reviewed.

**Pull request closed without merging**
