### PR TITLE
Added a default type to buttons to prevent autosubmission of forms

### LINKED ISSUE #3127: md-list-item secondary button submits form
Using a md-list with md-list-item inside a form with a secondary action assigned. Clicking the secondary action causes the form to submit.

Looking at the code the secondary action seems to wrap the element with the ng-click in a button - hence creating a submit button. You can not provide a default type="button"

### PR DESCRIPTION
**Pull request by gpit2286**
Fixes #3127

### CODE REVIEW

**Comment by gpit2286** [comment]
I signed it!

-- 
Kyle Baldwin
Sent with Airmail

On October 30, 2015 at 2:16:28 PM, googlebot (notifications@github.com) wrote:

Thanks for your pull request. It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

 Please visit https://cla.developers.google.com/ to sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Check your existing CLA data and verify that your email is set on your git commits.
If you signed the CLA as a corporation, please let us know the company's name.

**Comment by ThomasBurleson** [comment]
@robertmesserle - can you review ?

**Comment by robertmesserle** [comment]
LGTM

**Comment by robertmesserle** [comment]
Just make sure to include a BREAKING CHANGE note to the commit message when you merge it

**Comment by chrislambe** [comment]
Is there a good reason to have deviated from the HTML spec here? I get that people may not know or like the behavior, but it is clearly documented in the spec.

The relevant section, for reference:
http://www.w3.org/TR/html5/forms.html#the-button-element

> The missing value default is the Submit Button state.

*Edit:* For what it's worth, I was just bitten by this in 1.0.0-rc3. I'm going to have to find all the form submission buttons in my app and update the markup to adapt to this non-spec behavior.

**Comment by gpit2286** [comment]
I'll be honest and say I didn't check the spec before I submitted that fix.  It seems illogical to have a button default to a non-idempotent behavior.  It's probably am artifact from when buttons only submitted and reset forms.  Other than my personal dissent to the spec, no I don't think it should go against it.  In a perfect world, though, people would explicitly define types which would have made both the original problem and post-pull request work fine for everyone.

**Pull request closed without merging**
