### PR TITLE
fix(sidenav): Only restore focus if user interaction was keyboard

### LINKED ISSUE #5563: md-toolbar and sidenav focus problems
For testing purposes I tried to create a ```sidenav```, which should be triggered by the ```toolbar```
But as you can see in the bad quality GIF, the css class ```is-focused``` will be added after dismissing the sidebar. So I already checked the code and I found this snippet
````
return $q(function(resolve){
  // Toggle value to force an async `updateIsOpen()` to run
  scope.isOpen = isOpen;

  $mdUtil.nextTick(function() {
    // When the current `updateIsOpen()` animation finishes
    promise.then(function(result) {

      if ( !scope.isOpen ) {
        // reset focus to originating element (if available) upon close
        triggeringElement && triggeringElement.focus();
        triggeringElement = null;
      }

      resolve(result);
    });
  });

});
```
![gif](https://i.gyazo.com/42f9eaa131791d1431aeaf0d64f696cf.gif)

I already fixed that in my version, but I want to ask the development team first about their thoughts.
So I created a merge for that, please take a look at it and tell me more about potential side-affects

@jelbourn @ThomasBurleson

### PR DESCRIPTION
**Pull request by DevVersion**
Normally the Sidenav restores every time the last active element, so the focus won't disappear from the triggered button after closing the sidenav

Fixes #5563

### CODE REVIEW

**Comment by DevVersion** [comment]
I want to point to @marcysutton, what do you think?

**Comment by ThomasBurleson** [comment]
@DevVersion - what do you mean point-to ? @marcysutton can you review this PR ?

**Comment by marcysutton** [comment]
I am currently traveling but I will review it when I get a chance.

**Comment by DevVersion** [comment]
@ThomasBurleson Yeah I mean she should review my PR, and I have a little question, what means the new label?

@marcysutton, @ThomasBurleson: I will try to improve / refactor that code

**Comment by DevVersion** [comment]
I created a second PR to fix that issue. This time its a feature which can be used in other components too (my favorite one). It got already tested manually.

**Comment by EladBezalel** [comment]
@DevVersion as #5589 is the active PR can i close this one?

**Comment by DevVersion** [comment]
@EladBezalel Yes, I prefer the #5589 PR, but keep this PR open, I'm still waiting for a decision, which variant we will take

**Comment by DevVersion** [comment]
I think that's definitely the wrong way of implementation, so I will close this for cleanup purposes

**Pull request closed without merging**
