### PR TITLE
Minor

### PR DESCRIPTION
**Pull request by dattatrey93**

### CODE REVIEW

**Comment by DevVersion** [comment]
@dattatrey93 Seems like you unintentionally created a PR, which tries to merge `minor` into `master`.

**Comment by dattatrey93** [comment]
@DevVersion ,i tried intentionally to fork a branch locally but not tried to merge into master .

**Comment by dattatrey93** [comment]
i think it happened unintentionally due to some mistake

**Comment by DevVersion** [comment]
@dattatrey93 Not a problem, I just closed your PR, to keep the queue clean :)

**Pull request closed without merging**
