### PR TITLE
docs(md-icon) fix grammar and punctuation errors

### PR DESCRIPTION
**Pull request by noderat**

### CODE REVIEW

**Comment by clshortfuse** [comment]
Thanks for this. You shouldn't remove the comma in the sentence since, gramatically, you'd be describing developers as font-icons. :)

**Comment by noderat** [comment]
Ah, you're correct! I'll fix that up when I'm off mobile.

**Comment by DevVersion** [comment]
@noderat Any updates on that PR?

**Comment by noderat** [comment]
Apologies, I've added the comma back in the last commit.

**Pull request merged**
