### PR TITLE
fix(input): calculate icon vertical offset

### LINKED ISSUE #5731: Md-icon with md-input vertical align
The md-icon used with md-input is not correctly vertical centered.(Too high from text label)

Viewable on actual demo.

### PR DESCRIPTION
**Pull request by DevVersion**
This centers the icon in the middle as required.

Fixes #5731

### CODE REVIEW

**Comment by DevVersion** [comment]
This is a simple calculation, should be easy to review. @EladBezalel (I hope it's okay if always ask you for reviewing :smile:)

**Comment by EladBezalel** [comment]
@DevVersion Np feel free! i would need to test it locally.

**Comment by DevVersion** [comment]
Great :smile: You can simply build the docs to see the calculation in action,.

**Comment by DevVersion** [comment]
**Update**: Rebased to `master` due resulting conflicts.

Before fix: 



After calculation PR:

**Comment by EladBezalel** [comment]
@DevVersion it's not aligned accourding the spec,
image

image2

**Comment by DevVersion** [comment]
Okay, I will rework that.

PS: Thanks for reviewing so much!. Now I have much things to do in the next days :+1:

**Comment by EladBezalel** [comment]
NP :)

**Comment by DevVersion** [comment]
Okay, so now it should use `8px` in scale. See here a few measurements.

**Comment by DevVersion** [comment]
Can you please review @EladBezalel

**Pull request closed without merging**
