### PR TITLE
update(demo, dialog):moved padding to class and removed padding from element

### PR DESCRIPTION
**Pull request by EladBezalel**
closing #3963

### CODE REVIEW

**Comment by jelbourn** [comment]
The documentation should mention this class if it's meant to be consumed by users.

**Comment by ThomasBurleson** [comment]
@EladBezalel - 3 tasks:

* can you include some doc changes to mention this new `.md-dialog-content` class.
* can you squash your comments.
* please update with current rebase from master.

**Comment by EladBezalel** [comment]
@ThomasBurleson where should I doc it?

**Comment by ThomasBurleson** [comment]
Ideally it should go in a CSS doc similar to https://material.angularjs.org/0.11.2/#/CSS/button.  Something like `#/CSS/dialog` with a sample override and snapshot of its effects.

But perhaps [for time sake] just a paragraph to show here: https://material.angularjs.org/0.11.2/#/api/material.components.dialog/service/$mdDialog

**Pull request closed without merging**
