### PR TITLE
feat(md-contact-chips): add support for md-add-on-blur

### LINKED ISSUE #10008: mdContactChips: add support for md-add-on-blur
**Actual Behavior**:
 -  `What is the issue? *` The `md-contact-chips` component does not have support for `md-add-on-blur`.
 -  `What is the expected behavior?` When using a `md-contact-chips` component with the `md-add-on-blur` attribute, the 'selected' match is added when the component is blurred.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` Demo of the `md-chips` component with `md-add-on-blur`: [codepen](https://codepen.io/anon/pen/woGzBv). Demo of the `md-contact-chips` component lacking the `md-add-on-blur` functionality: [codepen](https://codepen.io/anon/pen/xRVEbW).
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chromium
 -  `Browser Version: *` 53
 -  `OS: *` Ubuntu
 -  `Stack Traces:`

Related issues: 

- issue for `md-chips` component: #3364 
- PR implementing the feature for `md-chips` component: #9095. 
- the need for support for the `md-contact-chips` was raised [earlier](https://github.com/angular/material/pull/9095#issuecomment-240880260).

### PR DESCRIPTION
**Pull request by Frank3K**
Add support for the md-add-on-blur attribute on md-contact-chips, in line with md-chips.

Closes #10008.

### CODE REVIEW

**Comment by Frank3K** [comment]
@DevVersion: could you please review?

TODO:

- [ ] add tests

**Comment by DevVersion** [comment]
@Frank3K Yeah. Please keep in mind that there is already a PR for the `add-on-blur` behavior in combination with an autocomplete.

- See Pull Request: https://github.com/angular/material/pull/9949

**Comment by Frank3K** [comment]
@DevVersion: missed that one... Do you think we only need the changes in `src/components/chips/js/contactChipsDirective.js` after #9949 in merged?

**Comment by DevVersion** [comment]
@Frank3K Sorry for the late response. Yeah I'd say that would be good.

**Comment by Frank3K** [comment]
@DevVersion: I'll wait till after #9949 is merged. Then I will adapt, test and update the PR.

**Comment by DevVersion** [comment]
@Frank3K Sounds good. Thank you!

**Comment by Frank3K** [comment]
Since #9949 was [merged](https://github.com/angular/material/commit/72264aff108319ef7d8fe2e530fba1e713daec5a) I have looked at this PR. There are a number of issues I would like to discuss:

1. The `addOnBlur` property is parsed as boolean attribute [as follows](https://github.com/angular/material/blob/72264aff108319ef7d8fe2e530fba1e713daec5a/src/components/chips/js/chipsController.js#L62-L63):

```js
  /** @type {string} */
  this.addOnBlur = $mdUtil.parseAttributeBoolean($attrs.mdAddOnBlur);
```

I can not get this working by passing it as an attribute on `md-contact-chips` like [this](https://github.com/Frank3K/material/blob/15f251435351b3ca5d3572568841d8adb618e7b3/src/components/chips/js/contactChipsDirective.js#L58):

```html
        md-add-on-blur="$mdContactChipsCtrl.addOnBlur"\
```

The string "$mdContactChipsCtrl.addOnBlur" gets parsed as boolean this way.

It does work when I add `addOnBlur: '=?mdAddOnBlur'` to the [scope](https://github.com/Frank3K/material/blob/15f251435351b3ca5d3572568841d8adb618e7b3/src/components/chips/js/chipsDirective.js#L225-L240) of the `md-chips` directive. The _parseAttributeBoolean_ needs to be removed in this case. I do not know why the _parseAttributeBoolean_-approach is used instead of a regular scope parameter.

2. Your [PR introduced](https://github.com/DevVersion/material/blob/b6a6b302dc5e7756cde1dd028f94caeff9c245c0/src/components/chips/js/chipsController.js#L607) a requirement on `requireMatch`: it should be false in order to use the add-on-blur-functionality. In the case of `md-contact-chips` I think this requirement is contra-productive: I (or: the user) would assume that 'on-blur' the selected item from the autocomplete is added.  What do you think?

3. We can not use the chipBuffer to add contact-chips, since contact-chips are objects and the chipBuffer is a string. Therefore, the current PR (which does not merge), has the [following code](https://github.com/Frank3K/material/blob/15f251435351b3ca5d3572568841d8adb618e7b3/src/components/chips/js/chipsController.js#L547-L551):

```js
    if (this.autocompleteCtrl) {
      var index = this.autocompleteCtrl.index;
      if (index >= 0) {
        this.autocompleteCtrl.select(index);
      }
    } else {
      this.appendChip(chipBuffer);
      this.resetChipBuffer();
    }
```

Do you think this is OK and should I update it or do you know a better approach?

**Comment by Splaktar** [comment]
Please see https://github.com/angular/material/issues/10008#issuecomment-382880887 for the reasoning behind closing this and add any discussion to that issue rather than this PR.

**Pull request closed without merging**
