### PR TITLE
enhance(dialog): add option focusCloseBtn=true

### PR DESCRIPTION
**Pull request by wuv1982**
alter this option to support customize focus.
e.g. let input text get the focus by default

### CODE REVIEW

**Comment by wuv1982** [comment]
i have just signed the CLA

**Comment by marcysutton** [comment]
I think it would be better to supply an element to focus rather than opting out entirely. Focus management is very important to the dialog, so it shouldn't be so easy to turn off.

**Comment by wuv1982** [comment]
I tried to use a customize directive `my-focus` to set the focus on my element , but `closeButton.focus();` always force the focus on the `CloseBtn`. 
I just want a way to avoid this behavior and set the focus on my element in this case.

Also, I think it is a good idea for setting the focus on `CloseBtn` by default for almost the using cases.
So I use a option to opt the choice.
If u don't like the `option` , i think remove the force focus behavior maybe better.

**Comment by wuv1982** [comment]
thanks for accepting

**Pull request closed without merging**
