### PR TITLE
feat: BiDirectional Provider to fix bi-directional problem + md-tabs ink bar for RTL pages

### LINKED ISSUE #1080: Add bidirectional support for all components
Most of the components support rtl but there are some components that don't work properly,

for example #964, #1068 or in the [list component ](https://github.com/angular/material/blob/629b753ff348b805e4ff73a2f66d354f2d42841d/src/components/list/list.scss#L42) that supports only ltr and needs to be overridden for fix.

bidirectionally

### PR DESCRIPTION
**Pull request by mohebifar**
These commits fix #1080 basic issue by defining a new provider named `$mdBiDirectionalProvider`. You can use this provider to set direction of your page.

```js
app.config(function($mdBiDirectionalProvider) {
  $mdBiDirectionalProvider.rtlMode(true);
}
```

By now #1078 is fixed.

[Review on Reviewable](https://reviewable.io/reviews/angular/material/1711)

### CODE REVIEW

**Comment by mohebifar** [comment]
Hi

I've already signed the CLA.

Thank you in advance.

Best,
Mohamad Mohebifar

**Comment by ThomasBurleson** [comment]
@mohebifar - This PR is only a partial solution to the Bidirectional issues. You are addressing only the inkBar issue. There will also be text layouts for radio buttons, checkboxes, etc. 

A PR for this issue must be more complete **or** the team must also ready to incorporate your idea (here) into a full solution. I will mark your PR to be used in Milestone 0.10.  Thank you.

**Comment by mohebifar** [comment]
I just wanted to design an approach to this issue. So is there any possibility to anticipate this PR's milestone if I make it more complete ?

**Comment by ThomasBurleson** [comment]
We are postponing BiDi until post 1.0.

**Comment by EladBezalel** [comment]
Closed with SHA 08bf4f9 #7245

**Pull request closed without merging**
