### PR TITLE
Mention dependency on angular-messages

### PR DESCRIPTION
**Pull request by jadjoubran**
As discussed in #1284

### CODE REVIEW

**Comment by jadjoubran** [comment]
I signed it!

**Comment by Frank3K** [comment]
I think it would be an improvement if a link to the [docs at AngularJS](https://docs.angularjs.org/api/ngMessages) is added, since that contains instructions on how to install and on how to use it.

**Comment by jadjoubran** [comment]
Added, thanks @Frank3K

**Comment by EladBezalel** [comment]
Please read our [Contributing guidelines](https://github.com/angular/material/blob/master/CONTRIBUTING.md)

**Comment by ThomasBurleson** [comment]
@jadjoubran  - This is a good addition to the sample. Thx.

**Pull request closed without merging**
