### PR TITLE
fix missing tabsdemoStaticTabs class in index.html

### PR DESCRIPTION
**Pull request by singalongwithme**
I was playing around with the tabs demo in my application and got hung up on the css component of the static tabs. The reason why the specific animation does not work is because the html is missing a class on the outer div. I'm not sure if this is by purpose or not, but I did get hung up on it and if this was just a hiccup, then I added the class to the html. Everything works great by the way!

### CODE REVIEW

**Comment by marcysutton** [comment]
@singalongwithme I'd like to merge this, can you sign the CLA?

**Comment by singalongwithme** [comment]
Hey Marcy!

Thanks for reviewing my pull and glad to hear you want to merge. I believe
I've signed the CLA when I made the initial pull. My records say I signed
it at 12:16 PST.

**Comment by marcysutton** [comment]
Sweet, thanks!

**Comment by marcysutton** [comment]
Closed with b809f4737db4a754e851bb7569462a000f3475b8

**Pull request closed without merging**
