### PR TITLE
fix(datepicker): Set vertical align on datepicker tables

### LINKED ISSUE #7111: md-[datepicker-]calendar table elements are dependent on browser defaults
Particularly tbody, td, tr rely on the default vertical-align:middle style.
This is incompatible with popular CSS resets that use vertical-align:baseline as the standard, e.g. http://meyerweb.com/eric/tools/css/reset/

Headers are misaligned vertically with vertical-align:baseline
datepicker screenshot

md-calendar-specific table element rules with vertical-align:middle would make this less fragile

### PR DESCRIPTION
**Pull request by jshoudy11**
fixes #7111

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@conniew - is this ready for me to merge? LGTM

**Comment by jshoudy11** [comment]
@ThomasBurleson I don't think this is a breaking change. It doesn't change the appearance on material.angularjs.org, only for those that have vertical-align:baseline set explicitly.

**Comment by conniew** [comment]
The code LGTM, I trust you and Jake more with the process of merging, though.

**Comment by jshoudy11** [comment]
@ThomasBurleson do you want me to push this through the command line from jshoudy11:feat/datepicker_align to angular:feat/datepicker_align and then create a PR to pull it into master separately? Or should that all be done from this PR?

**Comment by ThomasBurleson** [comment]
@jshoudy11, @conniew - I was only going to merge this into `master` and `minor` branches.

**Comment by jshoudy11** [comment]
@ThomasBurleson Okay. Should be ready for merge then.

**Pull request closed without merging**
