### PR TITLE
fix(button): icon in icon-button not centered vertically

### PR DESCRIPTION
**Pull request by aldeso**
`md-icon-button` currently the icon is  not centered vertically

Fix line-height value to 100%

### CODE REVIEW

**Comment by DevVersion** [comment]
@aldeso In my case the icons inside an icon button are correctly centered. Which browser are you using?

**Comment by aldeso** [comment]
Hi DevVersion, tested on IE11, Chrome and Edge...

**Comment by aldeso** [comment]
Hi @ all, the problem also corresponds to the vertical-align property (middle) of 'md-icon'.

**Comment by ThomasBurleson** [comment]
@aldeso - please rebase with HEAD.

**Comment by ThomasBurleson** [comment]
Closing as too risky... scope is too large.

**Pull request closed without merging**
