### PR TITLE
update(interimElement): added missing scope dispose to fix memory leak

### PR DESCRIPTION
**Pull request by imdark**
see #9677

### CODE REVIEW

**Comment by imdark** [comment]
I signed it!

**Comment by ThomasBurleson** [comment]
@DevVersion - please elaborate re "PR needs a PR...".

**Comment by DevVersion** [comment]
@ThomasBurleson Sorry it was meant to be `needs a rebase`

**Comment by imdark** [comment]
I have fixed the conflicts

**Comment by ThomasBurleson** [comment]
@imdark - please squash your commits so our testing and merge process is easier. Thank you.

**Comment by imdark** [comment]
@ThomasBurleson is this ok?

**Comment by imdark** [comment]
@ThomasBurleson, @DevVersion
Do you guys need me to do something else about this?

**Comment by DevVersion** [comment]
@imdark The PR is fine 👍 - It is planned to get it into v1.1.2 soon.

**Pull request merged**
