### PR TITLE
fix(select): fix cycle option focus after keyboard search

### PR DESCRIPTION
**Pull request by brandom**
After keyboard search option focus cycling would start from previously focused element

[Review on Reviewable](https://reviewable.io/reviews/angular/material/2616)

### CODE REVIEW

**Comment by brandom** [comment]
@googlebot Added primary Github email to CLA.

**Comment by ThomasBurleson** [comment]
@brandom - You need to sign a CLA for account also.

**Comment by brandom** [comment]
@ThomasBurleson The first commit that did not pass was accidentally committed under my work email address. I just added the email address to my Github account as well as the CLA. Do I need to create another PR or will @googlebot pick this up?

**Comment by ThomasBurleson** [comment]
@rschmukler - can you review this?

**Comment by rschmukler** [comment]
@brandom LGTM, merged! Thanks!!

**Comment by brandom** [comment]
@rschmukler Thanks! This branch has another commit for the same component that was not merged. Was this intentional?

**Comment by rschmukler** [comment]
@brandom cc8850b3138e14f8070df3a91fe1114bec192ff3 and 3e3eb9efe18c7704b74533a80ff282a0959af9d8 both made it in, did I miss something else?

**Comment by brandom** [comment]
@rschmukler Odd, github says the branch has unmerged commits and I only see 3e3eb9e in this thread. However clicking the link for cc8850b proves this is not the case so carry on :+1:

**Pull request closed without merging**
