### PR TITLE
Added $mdSideSheet

### PR DESCRIPTION
**Pull request by jmcpeak**
I use this type of object as a replacement for $mdDialog.

Complete with documentation and example.

Future features would be the ability for the user to change the width.
Maybe a small tab indicator image, allowing it to be visually closed by the user, but the promise is not resolved/rejected until hide() or cancel() are called.

### CODE REVIEW

**Comment by jmcpeak** [comment]
I signed it!

**Comment by jmcpeak** [comment]
I signed it!

**Comment by jmcpeak** [comment]
here

**Comment by jmcpeak** [comment]
here to confirm

**Comment by jmcpeak** [comment]
I signed it!

**Comment by ThomasBurleson** [comment]
@jmcpeak - please rebase from master and squash your commits.

As we approach release v1.0, our team is focusing on quality, performant, core components specified in Material Design. Is the SideSheet an articulated component? Or is this a variant of SideNav ?

**Comment by jmcpeak** [comment]
So ideally, I think there should just be a `$mdSheet` (`$mdBottomSheet` would be deprecated).

$mdSheet has all the properties of `$mdDialog` along with a new one - `openDirection: left, right, top, bottom`.

In the template it can also use a whiteframe `<md-sheet class="md-whiteframe-z3">` (like `$mdSidenav`)

`$mdSidenav` would still exist, but would use the underpinnings of `$mdSheet`.

**Comment by EladBezalel** [comment]
@jmcpeak please rebase,
why sidesheet isn't the same as sidenav??

**Comment by EladBezalel** [comment]
closing due to inactivity

**Pull request closed without merging**
