### PR TITLE
feat(calendar): Add date completion detection

### PR DESCRIPTION
**Pull request by mhchen**
Provide (very) basic detection to see if a string contains enough
information to be considered a date. Used to set the ngModel value when
the input is being updated.

### CODE REVIEW

**Comment by mhchen** [comment]
@jelbourn Please review at your convenience

**Comment by jelbourn** [comment]
Could you rebase? I just pushed some changes for review feedback, fixed the unit tests, and rebased on master.

**Comment by mhchen** [comment]
@jelbourn Done

**Comment by jelbourn** [comment]
LGTM; will merge now

**Comment by jelbourn** [comment]
Closed via 731fe9811adf3a65a6562452273b698cd69038a5

**Pull request closed without merging**
