### PR TITLE
docs(): Demo descriptions, bugfixes

### PR DESCRIPTION
**Pull request by marcysutton**
Per https://github.com/angular/material/issues/1058#issuecomment-68535060, demos can now display a `readme.md` file for each demo. Also includes a fix for the "View on Github" button and style bugs. (https://github.com/angular/material/issues/898, https://github.com/angular/material/issues/897).

### CODE REVIEW

**Comment by gkalpak** [comment]
Unless I am missing something, the contents won't be interpreted as Markdown (but HTML).
Why have an `md`  extension ?

**Comment by marcysutton** [comment]
It was originally intended that way, but I didn't want to pull in dependencies to parse Markdown. So it should be changed to `.html` and identified from the filename: `readme.html`.

**Comment by gkalpak** [comment]
:+1:

**Comment by marcysutton** [comment]
@rschmukler the `hasDemo` issue should be fixed.

**Pull request closed without merging**
