### PR TITLE
fix(theme): change hardcoded hue-3 values for background color to backgr...

### PR DESCRIPTION
**Pull request by arshabh**
fix(theme): change hardcoded hue-3 values for background color to color

Closes: #1450

### CODE REVIEW

**Comment by rschmukler** [comment]
@arshabh this looks good, but what is actually changing `background-color` into the proper color? Could you add that functionality?

**Comment by arshabh** [comment]
Hey @rschmukler, take a look at the file `theming.js` - line no. 363 - `function parseRules()` takes care of parsing these css rules. It creates a regex by the name `simpleVariableRegex` which replaces specific hues that have been specified explicitly like `{{background-hue-3}}` or `{{primary-100}}`. It also defines a regex by the name `hueRegex` which looks for eg `{{background-color}}` or `{{primary-contrast}}` etc.. and puts in proper color with line no 397.

**Comment by rschmukler** [comment]
@arshabh Right, but usually for `background-color` it will put in the `default` hue for that palette. In this case `500`. That ends up being a different color than `hue-3 (A100)`, which results in the background color being changed to not white, right?

**Comment by arshabh** [comment]
@rschmukler No that does not seem to be the case - `background-color` would enable the parser to put in all hues in place i.e. `hue-1`, `hue-2` and `hue-3`. That is what happens after line no. 397. So the resulting class would look something like this - `md-default-theme .md-hue-1`, `md-default-theme .md-hue-2` and `md-default-theme .md-hue-3` - with their background color as per the specified hue. Only `.md-default-theme` would get the `default` hue for itself.

**Comment by rschmukler** [comment]
@arshabh the issue is that the `default` hue color for the background palette is currently `500` which would cause most people's expected white background to turn grey. I've changed the default background palette and will now merge this in.

**Comment by arshabh** [comment]
@rschmukler yes, pardon me for not confirming to that in my previous statement - yes the default color would not be white and some thing greyish.

**Comment by Jonybang** [comment]
Now the same problem on [sidenav theme](https://github.com/angular/material/blob/e3b0cd8a143086bb3e5173b8d30f2cc8e8e42eca/src/components/sidenav/sidenav-theme.scss).
Please, fix this.

**Pull request closed without merging**
