### PR TITLE
fix(datepicker): ensure the element always blends in with it's parent

### LINKED ISSUE #7502: md-date-picker no longer transparent
My datapicker used to be transparent (i have it in a card that has a white background):

image

No it has a slight grey color to it..

### PR DESCRIPTION
**Pull request by crisbeto**
fix(datepicker): ensure the element always blends in with it's parent
* Makes the datepicker component transparent so it always blends in with it's parent.
* Prevents the content around a datepicker from jumping when it gets opened.

Closes #7502.

### CODE REVIEW

**Comment by topherfangio** [comment]
I am not sure this is ready quite yet. If I manually set the background of my container to something like pink, there is still some part of the datepicker that is set to an incorrect color.

datepicker-background

**Comment by crisbeto** [comment]
I'm not quite sure that we'd be able to accommodate for all of these cases though (e.g. a grandparent having a background etc.). The alternative could be to set it as transparent and have it inherit only when it's open?

**Comment by topherfangio** [comment]
I think transparent is okay, but I currently don't understand why we're even setting the background for input elements at all. Is there ever a case in the spec where it doesn't have the same background as the parent container?

**Comment by crisbeto** [comment]
I don't think so. I'll make it transparent and try out a few more scenarios just in case.

**Comment by crisbeto** [comment]
I've updated it @topherfangio. Now it's transparent when closed and when it's open, it uses the body background. I also managed to fix an issue where the datepicker would push it's surrounding content when it gets opened.

**Comment by topherfangio** [comment]
LGTM :+1:

**Pull request closed without merging**
