### PR TITLE
test(sticky): introduce spec for mdSticky

### PR DESCRIPTION
**Pull request by matthewrfindley**
This is a preemptive change to support further bug fixes and additional feature work for mdSticky.

[Review on Reviewable](https://reviewable.io/reviews/angular/material/2301)

### CODE REVIEW

**Comment by matthewrfindley** [comment]
Travis CI reports that the build passed, however it actually failed when running on Firefox (for good reason).

**Comment by matthewrfindley** [comment]
Specs are failing since they run on FF.  The code under test is testing logic for browsers that do not support ```position: sticky```.  Is there an established pattern for testing browser specific features?

**Comment by matthewrfindley** [comment]
I realize I've introduced a behavior change when registering an item as a sticky.  The previous spec threw an error, so my assumption was the spec was correct in this case.

**Comment by ThomasBurleson** [comment]
@matthewrfindley  - considering the late arrival of this PR, we will delay merging until AFTER the 0.9 release this week.

**Comment by robertmesserle** [comment]
@ThomasBurleson @matthewrfindley LGTM!  Definitely seems like it will have future benefits - pre-emptive organization! :+1:

**Comment by ThomasBurleson** [comment]
@matthewrfindley - Nice work here. Sorry for the merge delays. 
Please rebase with master and I will merge.

**Comment by robertmesserle** [comment]
@matthewrfindley Sadly, this has fallen through the cracks for a bit.  When I rebased this PR, there are a number of Firefox failures when running Karma.  Can you rebase and see if there is any obvious reason for these failures?

**Comment by matthewrfindley** [comment]
Hey Robert,  

I did the rebase and appears that I may have overlooked the Firefox failures.  I don’t think that I had considered how to address those.

**Comment by ThomasBurleson** [comment]
@matthewrfindley - do you have time to resolve the FF test failures ? @robertmesserle - do you have time to help Matthew?

**Comment by EladBezalel** [comment]
@matthewrfindley do you mind rebasing ?

**Comment by EladBezalel** [comment]
closing due to inactivity

**Pull request closed without merging**
