### PR TITLE
feat(slider): add ability to specify a unit of measure

### PR DESCRIPTION
**Pull request by AMoreaux**

### CODE REVIEW

**Comment by AMoreaux** [comment]
I signed it!

Le mer. 22 févr. 2017 à 18:45, googlebot <notifications@github.com> a
écrit :

**Comment by ThomasBurleson** [comment]
@AMoreaux - Please provide 2 or more unit tests to verify these changes. Afterwards, we will review and (if passed) merge to master.

**Comment by ThomasBurleson** [comment]
@AMoreaux - please rebase and squash your commits.

**Comment by AMoreaux** [comment]
Squash, rebase, and tests. 👍 @ThomasBurleson

**Comment by Splaktar** [comment]
Thank you for fixing the `package-lock.json` issue. Now unfortunately the commits needs to be squashed again. Also the proper commit message of this one would be a single line with `feat(slider): add ability to specify a unit of measure`.

**Comment by AMoreaux** [comment]
hi @Splaktar . Sorry, I tried to squash my commit. But one of them is a merge. And I failed to squash them.

**Pull request closed without merging**
