### PR TITLE
docs(tabs): fix wrong aligned parameter.

### PR DESCRIPTION
**Pull request by chrisconover**
I noticed this param name was misaligned while reading the source.

### CODE REVIEW

**Comment by DevVersion** [comment]
@chrisconover Can you please amend your commit message using the commit guidelines.
```
docs(tabs): fix wrong aligned parameter.
```

Additionally, I'm not sure about those small PR's. So @ThomasBurleson should take a look at this.

**Comment by chrisconover** [comment]
Sure thing. Just updated the commit message.

**Comment by ThomasBurleson** [comment]
not valid

**Comment by chrisconover** [comment]
Hi there, can you help me understand why this isn't valid? I look at Angular Material all day and would love to help fix things that I see.

**Pull request closed without merging**
