### PR TITLE
Fix for required in autocomplete

### PR DESCRIPTION
**Pull request by chr22**
[Review on Reviewable](https://reviewable.io/reviews/angular/material/3366)

### CODE REVIEW

**Comment by chr22** [comment]
I signed it!

**Comment by tuhoojabotti** [comment]
Looks good!

**Comment by ThomasBurleson** [comment]
@tuhoojabotti - Please rebase with master and confirm that Travis builds properly for this PR.

**Comment by tuhoojabotti** [comment]
@ThomasBurleson I think you meant to ping @chr22

**Comment by ThomasBurleson** [comment]
@chr22 - Please rebase with master and confirm that Travis builds properly for this PR.
@tuhoojabotti - my apologies.

**Comment by robertmesserle** [comment]
These changes are already in master.

**Pull request closed without merging**
