### PR TITLE
fix(md-chips): change md-icon class to inherit size

### PR DESCRIPTION
**Pull request by batsauto**
fix(chips): md-chips remove icon not inheriting class size

This fix will allow the chip remove icon to inherit the proper size from the css class.

This addresses issue #9619

### CODE REVIEW

**Comment by topherfangio** [comment]
Looks good, but can you please update the commit message & PR description to follow our guidelines?

https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#submitting-pull-requests

Thanks!

**Comment by batsauto** [comment]
I updated the commit message and PR description

**Comment by batsauto** [comment]
I updated the commit message and PR description

**Comment by batsauto** [comment]
I updated the commit message and PR description

**Comment by topherfangio** [comment]
@batsauto Based on what I'm seeing in your changes, this should not be classified as a breaking commit because the user shouldn't need to change anything. Also, your description in the PR still says that you need to change `chips.scss`, but you've already done that.

Am I not understanding something?

Thanks!

**Comment by batsauto** [comment]
I am new to making PR and so I missunderstood what the purpose of the PR was and the commit comment. I believe I have everything sorted. Thanks for your understanding.

**Comment by topherfangio** [comment]
LGTM 👍

**Comment by Splaktar** [comment]
Feedback for presubmit failures: This PR "has mostly good looking screenshot diffs, except one app where the chip remove button isn't vertically centered." It's about 4px lower than it should be.

**Pull request merged**
