### PR TITLE
fix(virtualRepeat): Broken demos relating to size computation

### PR DESCRIPTION
**Pull request by kseamon**

### CODE REVIEW

**Comment by kseamon** [comment]
@ThomasBurleson @jelbourn

**Comment by kseamon** [comment]
@jelbourn I wasn't able to find the Issue for this either.

**Comment by jelbourn** [comment]
@kseamon This change is consistently timing out on travis.

**Comment by kseamon** [comment]
Perhaps debounce needs to be mocked out in all tests with a repeater now?

**Comment by kseamon** [comment]
Tests fixed

**Pull request closed without merging**
