### PR TITLE
chips: support Validation of a Minimum number of Chips

### PR DESCRIPTION
**Pull request by jotunnjs**

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@jotunnjs  - please  provide unit tests and squash your commits.

**Comment by jotunnjs** [comment]
I signed in

**Comment by jotunnjs** [comment]
Sorry, I haven't been doing requests to other libraries earlier. Please, tell me in what way should I provide you a unit test? It's already passed by Travis test.
And also this commit should be merged after this one https://github.com/angular/material/pull/10613
Thanks

**Comment by Splaktar** [comment]
Thank you for your contribution. Please follow the [commit message guidelines](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-commit-message-format).

I can point you to some steps for squashing your commits if you need. It may also be easier to just close this PR and create a new one with a single correct commit.

Please make sure that your change from https://github.com/angular/material/pull/10613 is also included in that one commit.

For the tests, you would want something like the [md-max-chips tests](https://github.com/angular/material/blob/master/src/components/chips/chips.spec.js#L933-L1045) but with tests that make sense for the minimum versus the maximum.

I'm going to go ahead and close this for now. Please open a new issue before submitting a PR, describe your desired feature and if possible how you would like to implement the API. Then we can help provide some feedback on the approach and whether or not we can consider accepting a PR for it.

**Pull request closed without merging**
