### PR TITLE
docs(theming): mention that the background palette will be used by md-content

### LINKED ISSUE #7168: using background theme
The documentation briefly mentions that it exists, but it is not clear how it should be used and on which items.

### PR DESCRIPTION
**Pull request by DevVersion**
There was currently not clarity about the background palette.

Questions like:
- How can I use the background color?

Fixes #7168

### CODE REVIEW

**Comment by EladBezalel** [comment]
Should be based on #7422

**Comment by DevVersion** [comment]
:+1: Yep

**Comment by ThomasBurleson** [comment]
`md-content` no longer defines use of background color; it inherits the background color from the `html` or `body` element background color. This means that the PR change above ^^ is misleading and not correct:

> The background palette will be always applied to the `md-content` directive

Here is the rule derivation:

1) Based on the default Angular Material configuration or a custom configuration of themes. Core.js specifies the **default** shipped with ngMaterial:

```js
  $mdThemingProvider.theme('default')
    .primaryPalette('indigo')
    .accentPalette('pink')
    .warnPalette('deep-orange')
    .backgroundPalette('grey');
```

2) The backgroundPalette used is `grey`; colors defined in `theme.palette.js`:
```json
'grey': {
    '50': '#fafafa',
    '100': '#f5f5f5',
    '200': '#eeeeee',
    '300': '#e0e0e0',
    '400': '#bdbdbd',
    '500': '#9e9e9e',
    '600': '#757575',
    '700': '#616161',
    '800': '#424242',
    '900': '#212121',
    '1000': '#000000',
    'A100': '#ffffff',
    'A200': '#eeeeee',
    'A400': '#303030',
    'A700': '#616161',
    'contrastDefaultColor': 'dark',
    'contrastLightColors': '600 700 800 900'
  },
```

The ngMaterial styles define background color in `themes.css` as:

```css
html, body {
  &.md-THEME_NAME-theme {
    color: '{{foreground-1}}';
    background-color: '{{background-50}}';
  }
}
```

So the `background-50` with the predefined `grey` palette will be **`#fafafa`**. 

> It is this color that is inherited for default, shipped ngMaterial themes.

**Comment by ThomasBurleson** [comment]
I think it will be worthwhile to document this for developers.

**Comment by DevVersion** [comment]
@ThomasBurleson That changed in Elad's PR, that's why this PR is now misleading.

I'm not sure where we should document that and how we explain that briefly. 

Since [Theming Introduction](https://material.angularjs.org/latest/Theming/01_introduction) quoutes:
> A theme also specifies a background color palette to be used for the application.
nobody knows where the background color pallete will / can be used.

**Comment by DevVersion** [comment]
Closing this PR, because it's outdated and there had been a lot of changes.

**Pull request closed without merging**
