### PR TITLE
chore(): cleanup dependencies

### LINKED ISSUE #7956: build: NPM deprecations
I just cloned the repo and reinstalled all NPM modules and was met with the following warnings about deprecated plugins.

We should investigate and see if we can upgrade these

```bash
Fast-forwarded master to 877551c5318ff6f6bd322d914567ecb7eaf41f29.
topher@Tophers-MBP:~/Documents/Development/Profoundry/angular/material$ rm -rf node_modules
topher@Tophers-MBP:~/Documents/Development/Profoundry/angular/material$ npm install
npm WARN deprecated gulp-minify-css@0.3.13: Please use gulp-clean-css
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
```

### PR DESCRIPTION
**Pull request by DevVersion**
```
Package                        Current   Wanted  Latest Location
---------------------------------------------------------------------------------
- [X] angularytics              0.3.0    0.3.0   0.4.0  angular-material-source
- [ ] conventional-changelog   0.0.17      git     git  angular-material-source
- [-] esprima                   1.2.5    1.2.5   2.7.2  angular-material-source
- [X] gulp-autoprefixer         1.0.1    1.0.1   3.1.0  angular-material-source
- [X] gulp-connect              2.3.1    2.3.1   4.1.0  angular-material-source
- [X] gulp-filter               1.0.2    1.0.2   4.0.0  angular-material-source
- [X] gulp-if                   1.2.5    1.2.5   2.0.1  angular-material-source
- [X] gulp-insert               0.4.0    0.4.0   0.5.0  angular-material-source
- [X] gulp-jshint              1.12.0   1.12.0   2.0.1  angular-material-source
- [X] gulp-ng-annotate          0.5.3    0.5.3   2.0.0  angular-material-source
- [X] gulp-ng-html2js           0.1.8    0.1.8   0.2.2  angular-material-source
- [X] jquery                    2.2.4    2.2.4   3.0.0  angular-material-source
- [X] jshint-summary            0.3.0    0.3.0   0.4.0  angular-material-source
- [X] karma                   0.13.22  0.13.22   1.0.0  angular-material-source
- [X] karma-firefox-launcher    0.1.7    0.1.7   1.0.0  angular-material-source
- [X] karma-jasmine             0.3.8    0.3.8   1.0.2  angular-material-source
- [X] karma-sauce-launcher     0.2.14   0.2.14   1.0.0  angular-material-source
- [X] lazypipe                  0.2.4    0.2.4   1.0.1  angular-material-source
- [X] lodash                   3.10.1   3.10.1  4.13.1  angular-material-source
- [-] merge-stream              0.1.8    0.1.8   1.0.0  angular-material-source
- [?] prompt-sync               1.0.0    1.0.0   4.1.4  angular-material-source
- [X] through2                  0.6.5    0.6.5   2.0.1  angular-material-source
```
X: Updated Package;
?: Not sure about update
-: Removed Package

Closes #7956

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@DevVersion  - This was not merged and introduces Karma failures. Please rebase and test.

**Comment by mgol** [comment]
Any news here? The tests pass.

**Comment by DevVersion** [comment]
@mgol Yeah I also cannot figure out any issues with the tests.

**Comment by ThomasBurleson** [comment]
Waiting on v1.1.0 to be released!

**Comment by jelbourn** [comment]
@DevVersion looks like this needs rebease

**Comment by DevVersion** [comment]
@jelbourn Done.

**Pull request merged**
