### PR TITLE
feat(tabs): add stretchHeight to fill parent element

### PR DESCRIPTION
**Pull request by imjoeco**
Use md-stretch-height to fill available space in parent element.

Closes won't fix issue #2254 abandoned by core team for material 2 surge. Previously approved for milestones 1.1.6 and 1.1.7 by @ThomasBurleson in pull request #9665 that was locked without explanation by @Splaktar.

### CODE REVIEW

**Comment by imjoeco** [comment]
@Splaktar Why'd you put a too heated tag on the last PR? Did you get mad? This is still as approved by @ThomasBurleson. I request that this PR be pushed through (or at least have the original unlocked so that someone can eventually push that through) as it does effect many devs as evidenced by issue #2254.

**Comment by Splaktar** [comment]
@imjoeco you closed the PR and stated "I am abandoning this for the foreseeable future". Your comments seemed to be rude and "heated" from my perspective. Sorry if I misread the emotion in your responses.

I was planning to make the required changes myself, as you invited me to do, but as you closed the PR twice, I understood that you no longer wanted this merged. I will close this PR, re-open and unlock the other, and then make the requested changes when I have time to do so.

If you have questions about things like this in the future, please ask them in the [forums](https://groups.google.com/forum/?pli=1#!forum/ngmaterial) rather than creating issues/PRs for questions.

**Comment by imjoeco** [comment]
@Splaktar Can you explain what was rude? Any emotion you attached to my response was of your own creation. You were the one who called your comments "nits" which is how I then referred to them.  Beyond that all my comment said was that I was currently too busy to address a bunch of non-issues that could just be picked up by a linter if I had your settings. None of you comments/change requests had anything to do with client facing code with the exception of the "md-block" issue in the demo which I did correct as it was my mistake. Even you said the functionality was sound and didn't request any logic changes aside from turning a `==` to a `===`. 

You were planning on making the changes yourself? Then why did you close the issue #2254 as "Won't Fix"? 

I look forward to your response.

**Comment by imjoeco** [comment]
@Splaktar You also gave me instructions me to make changes to the demo styling that would require testing without explaining why it was necessary. Those changes could have been made after merging my PR if you really thought they were necessary. I was already given an approval from @ThomasBurleson and asked to rebase and squash my branch for merge.

**Comment by Splaktar** [comment]
Prior approval does not matter. Thomas is no longer the maintainer of this library. 

I'm not sure if you realize it, but your tone is very aggressive. I understand that it took far too long to get your contribution merged and I appreciate your patience, but I am here trying to help you and I feel like you are always on the attack. I understand that above you seemed to indicate that you are not interested in how your statements affect my feelings, I would just like to point out that empathy is important, especially in open source.

I closed the issue as "Won't fix" because it appeared that you no longer had interest in getting the changes merged. I realize that you now want to get the changes merged.

I am locking this so that constructive conversation can happen in the new PR.

**Pull request closed without merging**
