### PR TITLE
fix(input): prevent duplicate showing duplicate messages

### LINKED ISSUE #6265: mdInputContainer: messages are displayed more than once
When an error in an `md-input-container` is triggered multiple times (e.g. when repeatedly changing the value using <kbd>backspace</kbd> and some other key) it is possible that the error message is displayed multiple times.

Issue tested on master. See the following screenshot:

ngmessage

### PR DESCRIPTION
**Pull request by DevVersion**
At the moment the both animation show / hide are running at same time.
That's why the client see's two messages at the same time.

Fixes #6265

### CODE REVIEW

**Comment by DevVersion** [comment]
Please check that out @Frank3K

**Comment by ThomasBurleson** [comment]
@topherfangio - please review.

**Comment by Frank3K** [comment]
Unfortunately the fix does not seem to work. 

Upon reading the code in the PR I see that the real work is done inside the function `hideMessage`, the other changes are only about setting and passing status variables. Upon inspection the function `hideMessage` is not triggered at all in my case (I have set a breakpoint on the first line).

**Comment by DevVersion** [comment]
The fix works not perfect (I will create another commit). But it works better than the old version.. now the messages are not appearing multiple times. `hideMessage` will be triggered in the ngMessageAnimation on `leave`.

**Comment by Frank3K** [comment]
You are right @DevVersion; for the demo the issue is indeed fixed.

For my own testcase the issue is not fixed, let me check what's the difference between those two...

**Comment by topherfangio** [comment]
@Frank3K - This may be a separate issue. We noticed recently that the animations are firing just fine within our demo application, but not when we open it as a separate Codepen. We are currently investigating what is causing this.

@DevVersion - I already talked to Thomas about this and I think a better solution would be to debounce the model changes so that the animations don't attempt to fire so often.

**Comment by Frank3K** [comment]
When trying to find out what the difference between my own testcase and the demo is I have found out that in the function `ngMessagesAnimation`:

- `enter` and `leave` do not trigger
- `addClass` and `removeClass` only trigger with `className` values `ng-active`, `ng-inactive` and `null`

I do not know if this is of any help...

**Comment by DevVersion** [comment]
@topherfangio Seems to be a good idea, but I think we should still provide a force show / hide to prevent that issue when using the class selector. 

If you want me to create a Pull Request for debouncing the Invalid Model, just tell me :smile:

**Comment by DevVersion** [comment]
I will close that PR, since @topherfangio is working on issues with ngMessages and debouncing the model will be even a better solution.

**Pull request closed without merging**
