### PR TITLE
fix(button) center contents in case of anchor tag.

### PR DESCRIPTION
**Pull request by ruiaraujo**
Possible fix for #1607

### CODE REVIEW

**Comment by iainmcgin** [comment]
I don't think this works, just tried it in my codepen: 
http://codepen.io/iainmcgin/pen/wBjqyB
The vertical alignment still seems off compared to md-button without href.

**Comment by iainmcgin** [comment]
Sorry, let me retract that: my codepen was not setting "vertical-align: middle" on the svg sub-elements like md-icon does. Your solution looks good.

**Comment by ruiaraujo** [comment]
Great, I also did a local test like yours on my own app but I didn't bother with a codepen example. Thanks for that!

I am quite interested in other solutions that don't involve settings fixed margins or something like that.
Let's see if any CSS wizard shows up and delivers.

**Comment by marcysutton** [comment]
Fixes were committed in a936e1edc964b69ffe5bf96905e348fc6f4c6b4d.

**Pull request closed without merging**
