### PR TITLE
Fix md-menu animation timeout issues

### PR DESCRIPTION
**Pull request by clshortfuse**
Fixes https://github.com/angular/material/issues/3892

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@clshortfuse - The issue with the animation timeout is a conflict between ngAnimate and ngMaterial's animation solution. We are preparing a full solution all ngMaterial animation.

**Comment by clshortfuse** [comment]
Are you sure this won't fix? I understand you're restructuring the animation system, but right now now md-menu does not work at all on devices that take longer than 370ms to animate (pretty much all mobile devices). 

I don't understand how this doesn't fix the issue.

When the timeout expires, it doesn't run the next piece of code because what equates to a single typo. It should call .finally instead of .then as it does with md-select.

**Comment by stevenmiles** [comment]
@clshortfuse Interestingly enough, I has been suffering blocking with md-select in 0.10.1-rc2 until it was fixed in 0.10.rc3

https://github.com/angular/material/commit/171b7ed874b3a29749628159afebcfb14d38cad9

I've just noticed this happening for mdMenu.

@ThomasBurleson 

Seems you fixed the md-select locking, thank you. I'm guessing the animation solution won't be released in between a release candidate and a release. This would a good short term fix until the animation solution appears, as was the case for md-select locking issue.

**Comment by KReden** [comment]
@ThomasBurleson Is there a time frame for this animation solution? If it is a ways off it might make sense to push a hotfix for this in the meantime, otherwise md-menu is pretty much broken on mobile and slower machines.

**Comment by ThomasBurleson** [comment]
@clshortfuse, @KReden, @stevenmiles - here is an interim fix to transitionEnd event timeouts [due to ngAnimate 1.4.x conflicts ]:  https://github.com/angular/material/commit/ce46a9a4ca49d88f0b58de5ebeada09971034682

> Btw, In our code base, using `finally()` is not a great solution for two (2) reasons:

*  The `finally()` handler function is not passed the result or error from the promise reject/resolve.
*  The `finally()` will not allow you to modify the value propagating. So rejections will continue to propagate.

**Comment by clshortfuse** [comment]
Thanks for the other workaround! It makes much more sense to never reject. I was aware of the fact finally would have its issues only after, when I learned about the then(successCallback, errorCallback) option.

**Comment by ThomasBurleson** [comment]
@clshortfuse - :+1: , `finally()` is a tricky one.

**Pull request closed without merging**
