### PR TITLE
Space input not working in contenteditable divs in md-list-item

### PR DESCRIPTION
**Pull request by thecas**
editable divs should also be escaped just like textarea and input.

### CODE REVIEW

**Comment by thecas** [comment]
I signed it!

**Comment by thecas** [comment]
I added my email!

**Comment by thecas** [comment]
I signed it!

**Comment by DevVersion** [comment]
I'm sorry to say that, but please close your pull request yourself, You trying to merge the build results into the ```master``` branch. But if you want to create a new pull request, please take a look at the committed files. (watch for ```angular-material.min.js``` and ```angular-material.js```)

**Pull request closed without merging**
