### PR TITLE
fix(dialog): correct opening position for showing a dialog

### LINKED ISSUE #1401: mdDialog: md-dialog-container problem on IE10
Normally, dialog container has CSS `top` parameter when you scroll down page, eg.:

    <div class="md-dialog-container ng-scope" style="top: 390px;">

On IE10, `top` is always set to `0`, so when you scroll page, you cannot see dialog window. After quick search, it looks problem is [here](https://github.com/angular/material/blob/master/src/components/dialog/dialog.js#L332).  `$("body").prop("scrollTop");` returns `0` on IE10.

### PR DESCRIPTION
**Pull request by yarl**
fixes fix #1401

### CODE REVIEW

**Comment by mramanauskas** [comment]
:+1:

**Comment by kschwidder** [comment]
Checked the code by copying the change into the current build. It is fixed !!!
BUT the backdrop is not properly painted :-) Does not matter for me. When can you release the fix ?

**Comment by marcysutton** [comment]
@kschwidder what do you mean by "backdrop is not properly painted"? Is that in a specific browser or OS?

**Comment by kschwidder** [comment]
When dialog is opened it looks like this
backdrop ok when not scolled

when browser has been scrolled and dialog is opened it looks this this
backdrop wrong after scrolling

**Pull request closed without merging**
