### PR TITLE
made ng-disable disable an anchor tag made by an md-button

### PR DESCRIPTION
**Pull request by dmarg**
Fix for issue #2490 look at ticket for description of issue. 

note: protractor not available so could not test click event

### CODE REVIEW

**Comment by dmarg** [comment]
I signed it!

**Comment by dmarg** [comment]
@ThomasBurleson I am just curious on when do you think this will be accepted and pulled into the project? Thanks

**Comment by dmarg** [comment]
@ThomasBurleson Thanks for closing this and writing the tests for this. I was unsure how the tests would work but now that I see how you did it makes a lot of sense.

Thanks!

**Comment by ThomasBurleson** [comment]
@dmarg - Thanks for the issue... **AND** the PR. That was very helpful.

**Pull request closed without merging**
