### PR TITLE
fix(fabSpeedDial): fix positioning for mixed button sizes

### LINKED ISSUE #3240: FAB Speed Dial: using md-mini and normal buttons together
Hi, when using normal buttons and `md-mini` together in the FAB Speed Dial, the mini buttons have offset to the left:

http://codepen.io/anon/pen/JdJBYR

### PR DESCRIPTION
**Pull request by cebor**
closes #3240

[Review on Reviewable](https://reviewable.io/reviews/angular/material/3427)

### CODE REVIEW

**Comment by Iniesta8** [comment]
very nice @cebor

**Comment by SimoKutlin** [comment]
Works like a charm! :+1:

**Comment by kas84** [comment]
How can you make its position fixed? Making it float so the fabSpeedDial is available no matter where your scroll is.

**Comment by cebor** [comment]
@kas84 just add some extra css rules

for example i use this for right-bottom positioning:

```css
.button-menu {
  box-sizing: border-box;
  position: fixed;
  white-space: nowrap;
  margin: 15px;
  z-index: 99;
  right: 0;
  bottom: 0;
}
```

**Comment by kas84** [comment]
Thanks @cebor . That works great for positioning.

FabSpeedDial is not working in Safari (mac & iOS)

**Comment by mohamadgithub** [comment]
I signed it

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/angular/material/3427)

**Pull request closed without merging**
