### PR TITLE
feat(chips): allow to specify md-max-chips attribute through md-contacts

### PR DESCRIPTION
**Pull request by kylekatarnls**
Hi,

We would need for a limit of the number of contacts. Could we pass the md-max-chips options from md-contacts to md-chips the same way than other options?

Sub-question: could it be tagged as a patch version?

Thanks,

### CODE REVIEW

**Comment by kylekatarnls** [comment]
I signed it!

**Comment by Splaktar** [comment]
Thank you for your contribution! Please follow the [commit message guidelines](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-commit-message-format) in the future.

**Review by Splaktar — CHANGES_REQUESTED** [review]
Can you please add a unit test to verify this functionality?

**Comment by Splaktar** [comment]
There were some issues with this PR that I have resolved in PR https://github.com/angular/material/pull/12050.

**Pull request closed without merging**
