### PR TITLE
fix(compiler): removed `@private` to fix dgeni failures

### PR DESCRIPTION
**Pull request by EladBezalel**

### CODE REVIEW

**Comment by mgol** [comment]
I added the `@private` keyword so that those methods are not publicly documented as they're supposed to be private.

Is there another way to achieve that?

**Comment by ThomasBurleson** [comment]
@mgol - AFAIR, we simply remove the `@ngdoc` notations. This keeps the method private but maintains the internal docs with returns/params and description.

**Comment by ThomasBurleson** [comment]
@EladBezalel - CI still failing on this one... any ideas why?

**Comment by mgol** [comment]
OK, in that case we'll need you, @EladBezalel to remove the `@ngdoc` pragmas.

**Comment by mgol** [comment]
@ThomasBurleson did you close it on purpose?

**Comment by ThomasBurleson** [comment]
@mgol - No, that was a click-mistake.

**Comment by EladBezalel** [comment]
@ThomasBurleson could seems to pass, I'll remove the @ngdoc notations

**Comment by ThomasBurleson** [comment]
@EladBezalel - as soon as the ngdocs are removed, we can test the docs build and mark this a presubmit.

**Pull request merged**
