### PR TITLE
fix(select): issue #2985 select multiple keypress

### PR DESCRIPTION
**Pull request by JerrodLong**
fix advancing selection when typing first char of option name when multiple matches exist

[Review on Reviewable](https://reviewable.io/reviews/angular/material/3016)

### CODE REVIEW

**Comment by JerrodLong** [comment]
Updated e-mail for CLA

**Comment by JerrodLong** [comment]
HI @rschmukler can you review this pull request and provide any feedback? Thanks!

**Comment by EladBezalel** [comment]
@JerrodLong first of all sorry for the delay!

Is there an issue about it?
couldn't figure from you description what's missing, 
please do check on HEAD if it's still a valid pr.

please rebase..

**Comment by ThomasBurleson** [comment]
Out-dated, invalid, or not core focus for Material 1.

**Pull request closed without merging**
