### PR TITLE
feat(componentRegistry): allow components to be accessed remotely

### PR DESCRIPTION
**Pull request by kennethcachia**
Initial version for #3520.

re: demos - do we need to expose an example for this on the docs?

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@kennethcachia - can you squash and rebase plz.

**Comment by kennethcachia** [comment]
Sure!

**Comment by EladBezalel** [comment]
@kennethcachia Can you please rebase?

**Comment by ThomasBurleson** [comment]
Will not merge.

**Pull request closed without merging**
