### PR TITLE
feat(bottomSheet): adds support for focusOnOpen

### PR DESCRIPTION
**Pull request by dmackerman**
This seems easy enough. I copied the pattern from `mdDialog`.

- [ ] write tests

[Review on Reviewable](https://reviewable.io/reviews/angular/material/2929)

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
And why do you want this optional?

**Comment by ThomasBurleson** [comment]
Refs https://github.com/angular/material/issues/2313

**Comment by dmackerman** [comment]
Not sure I get what you're asking? I want a way to disable all focus events for bottomSheet, so users can implement their own focus methods. By default it should focus, for accessibility (as mentioned in `mdDialog`) and for the majority of bottom sheet usage focus seems appropriate. Sorry if I misunderstood!

**Comment by ThomasBurleson** [comment]
@dmackerman - disregard my question, I found the original issue #2313 that discusses this. Thx

**Comment by marcysutton** [comment]
Should we take this one step further and implement something similar to mdSidenav, which has the `md-sidenav-focus` directive?

**Comment by dmackerman** [comment]
Up to you guys. This seems like a very lightweight option for now, but I can take a look at what it'd take to implement a similar `md-bottomsheet-focus` directive.

**Comment by ThomasBurleson** [comment]
@dmackerman - while this PR is nice. I do not think it is an API extension we want. I think `md-bottomsheet-focus` is right way to go. @see https://github.com/angular/material/blob/master/src/components/sidenav/sidenav.js#L136-L144.

If you want to submit a PR for that feature, I would gladly review and merge. Thanks.

**Pull request closed without merging**
