### PR TITLE
Allow support both horizontal and vertical swipe

### PR DESCRIPTION
**Pull request by Thaina**

### CODE REVIEW

**Comment by Thaina** [comment]
I have already sign that. Is it signed?

**Comment by Thaina** [comment]
#8879

**Comment by EladBezalel** [comment]
Horizontal and Vertical swipes are already [working](https://material.angularjs.org/HEAD/demo/swipe)

**Comment by Thaina** [comment]
@EladBezalel It cannot support both in the same element at the same time. We cannot start swipe in vertical by default. And we cannot start swipe in horizontal if we set it as vertical

Simply put, It has no basic drag functionality

**Comment by DevVersion** [comment]
Closing as in comment https://github.com/angular/material/issues/8933#issuecomment-234987351

**Pull request closed without merging**
