### PR TITLE
Wip/scroll fade toolbar

### PR DESCRIPTION
**Pull request by NickBolles**
Implement scroll-fade behavior on toolbars as discussed in #1054

modified from
http://codepen.io/jbltx/pen/KwQxBX

Related to #1053 #1259

I would love feedback on this and any suggestions!

Demos:
http://nickbolles.github.io/material/dist/demos/toolbar/

The new demos are:
demoScrollFade
demoScrollAway
demoScrollTabs (Not working yet I dont think, just threw this in at the end)

### CODE REVIEW

**Comment by NickBolles** [comment]
Also there are no tests for this yet. I'm assuming that will need to be done for sure before merging. I will work on this, although my experience with testing is next to none, it will be good practice :)

**Comment by ThomasBurleson** [comment]
Please rebase (from origin master) and squash your commits; after you includes tests. Thx.

**Comment by NickBolles** [comment]
Updated to include tests. There a few things that are not quite ready for prime time.
-The content is longer then the container sometimes, causing the toolbar to scroll off the screen. I am not quite sure how to fix this. I thought that using flex would fix it, but it didnt. I will be looking into this more.
- Displaying the picture in toolbar on desktop. How should this be handled? right now it just goes by the toolbar header and only shows the top amount of the picture.
- I started adding a `content-speed-factor` that could keep the top of the content visible untill the toolbar was completely condensed (by adding padding to the top of the content as you scroll) but it caused very very poor performance. So I commented it out for the commit. Ideas would be awesome for this. Possibly calculating the padding we need at the beginning and adding it then translating the content down as you scroll up
-tabs/search bar in the toolbar (this is more of a demo then an implementation, it should be doable with the current version

Let me know questions, comments, concerns and suggestions!

**Comment by NickBolles** [comment]
Here are the links to the demos:
- Simple Fade Demo: http://nickbolles.github.io/material/dist/demos/toolbar/demoScrollFade
- Fade Away Demo: http://nickbolles.github.io/material/dist/demos/toolbar/demoScrollAway
- Overlap Demo: http://nickbolles.github.io/material/dist/demos/toolbar/demoScrollOverlap
- Nested Demo: http://nickbolles.github.io/material/dist/demos/toolbar/demoNested

**Comment by NickBolles** [comment]
Also mobile performance is pretty poor. How can we improve this? It's not terrible but it definitely stutters when scrolled fast.

**Comment by ThomasBurleson** [comment]
@NickBolles  :+1: This looks impressive. I will test next week and merge if appropriate.

**Comment by NickBolles** [comment]
@ThomasBurleson have you had a chance to take a look at this? If so any questions, comments, concerns? 

My concern is that this isn't the best way to implement this. And that more of a "toolbar panel" approach would be better. Then the toolbar panel can control the toolbar flexible space and content inside it. Let me know your thoughts

**Comment by ThomasBurleson** [comment]
@NickBolles - Let me look at this tomorrow.

**Comment by NickBolles** [comment]
@ThomasBurleson sounds good!

**Comment by ThomasBurleson** [comment]
@NickBolles - As I mentioned I am very impressed with the effort and attention to detail you have invested in ScrollFade Toolbars. My concern is that these types of effects should not be hardcoded into Toolbar (with lots of control directives). 

Instead almost all of these effects (resizing, repositioning, alpha changes, color changes, etc) are typically seen in animation UX(es). Consider a animation timeline that animates from expanded to shrunk modes. The scrolling is effectively a manual scrubbing of the timeline between those two modes. 

I contend that the appropriate way to enhance the toolbar with transform effects (like scroll fade) is ngAnimate Timeline features; but those are not yet available.

> This weekend I will prepare a CodePen to show you exactly what I mean. And we can continue this discussion

**Comment by ThomasBurleson** [comment]
Once we identify an architectural approach that makes sense we can merge in your demos, etc. So this PR remains valuable and useful.

**Comment by NickBolles** [comment]
@ThomasBurleson Sounds good. As you can tell from my comments I was starting to see that my approach may not have been the best as I was completing it. I am interested to see your codePen. I have a feeling it will be something like whats in your repo here: https://github.com/ThomasBurleson/angularjs-gsTimelines

Which I had seen previously and am very interested in.

**Comment by NickBolles** [comment]
@ThomasBurleson I never heard back for a code pen on what you meant. (I'm sure your busy it's no problem) Just wondering why this was closed. If this isn't the way to go with the toolbar what would be the best way to go? Or is the material team going to add this feature soon?

**Comment by JunedS** [comment]
+1 

Hope to see this make soon to 1.0-rc1. Badly in need for this feature. I had done a temp work around but its not as polished as this. 

+1
+1
+1

Common let this happen! Btw good job NickBolles

**Comment by ThomasBurleson** [comment]
@NickBolles - the animation features with element anchoring will be added after the Angular Material v1.0 release.

**Comment by NickBolles** [comment]
Awesome. I will look at it and reevaluate this PR, unless this is going to be developed by the material team?

**Pull request closed without merging**
