### PR TITLE
fix(build): add @ngInject annotations everywhere

### LINKED ISSUE #7610: Many injected functions don't have @ngInject
A lot of functions that have injected services are annotated with @ngInject, but a lot aren't.

Closure compiler renames function arguments, so you need to add @ngInject to these for them to work after compilation.

### PR DESCRIPTION
**Pull request by crisbeto**
* Adds @ngInject to everything that was missing it.
* Removes any instances of @ngInject that were in the doc strings.
* Makes all the @ngInject declarations consistent with each other.
* Adds newlines at the ends of files that didn't have them and trims any excess whitespace.

Closes #7610.

This doesn't really need a whole lot of reviewing, but it might be a good idea to run a build locally, just in case and see whether Closure complains. It all seems fine locally with `gulp build-all-modules --mode=closure`, but I'm not too familiar with the build setup.

### CODE REVIEW

**Comment by topherfangio** [comment]
Regarding the portions where you moved it out of the ngdoc comment, can you revert those back so that they match the [style guide](https://google.github.io/styleguide/angularjs-google-style.html#nginject)?

**Comment by crisbeto** [comment]
Sure, but the ngdocs task throws warnings for some of them.

**Comment by topherfangio** [comment]
What is the warning?

**Comment by crisbeto** [comment]
That it's not a valid tag/annotation (I don't remember the exact wording).

**Comment by crisbeto** [comment]
Alright, I've put the ones that were in doc string back. I'll only move the one in `media.js` out because it throws the warning. Also here's what I was talking about, I think it only complains for those that get generated into pages:

```
warn:    Invalid tags found - doc "$mdMedia" (service)  - from file "src/core/util/media.js" - starting at line 4, ending at line 89
Line: 87: @ngInject ...
```

**Comment by ThomasBurleson** [comment]
@jelbourn - Is this an issue for you when do Closure builds on G3?

**Comment by ThomasBurleson** [comment]
This is not currently an issue within our build processes.

**Pull request closed without merging**
