### PR TITLE
feat(dialog): added fullscreen option to dialog

### LINKED ISSUE #2148: adding fullscreen option for mobile to $mdDialog
Hello,
I would like to know if you plan to include a fullscreen option to $mdDialog with some more responsive functionalities? Would be very great for using dialogs on mobile devices:

screen shot 2015-04-03 at 8 37 49 am

http://www.google.com/design/spec/components/dialogs.html#dialogs-full-screen-dialogs

Thanks for your great work!

### PR DESCRIPTION
**Pull request by EladBezalel**
Added `fullscreen` option that if it's set to true `.md-dialog-fullscreen` class is added to `<md-dialog>` that maximizing the dialog to the whole screen.

fixes #2148

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
I will change this to be consistent with Layouts and md- attributes:  `md-fullscreen-sm`

**Comment by EladBezalel** [comment]
fullscreen is only dialog feature, are you sure it should be in layouts?

**Comment by ThomasBurleson** [comment]
I am sure that if you are using a breakpoint syntax then we must be consistent.

**Comment by EladBezalel** [comment]
how are you going to implement it? 
`md-fullscreen-sm` is too specific.

**Pull request closed without merging**
